// Pipeline + interpreter scaffold generated by rdp-gen — this file is not regenerated; edit freely.
// Steps: 1) define ArithResult fields  2) fill in validate()  3) fill in eval functions
//        4) remove eslint-disable-next-line comments

import {
  ArithParser,
  type ExprNode,
  type TermNode,
  type FactorNode,
  type NumberNode,
  type DigitNode,
  type WspNode,
} from './ArithParser.js'
import { RDParserException } from '@configuredthings/rdp.js'

// ── Types ────────────────────────────────────────────────────────────────────

/**
 * Domain representation produced by the final pipeline stage.
 *
 * Replace this empty interface with the fields you want {@link transform} to return.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface ArithResult {
  // TODO: define your domain type
}

/**
 * A single semantic error found during {@link validate}.
 */
export interface ValidationError {
  message: string
}

// ── Stage 1: parse ───────────────────────────────────────────────────────────

/**
 * Stage 1 — parse `input` into a typed parse tree.
 *
 * @param input - Source string to parse.
 * @returns The root {@link ExprNode} of the parse tree.
 * @throws {SyntaxError} If `input` does not match the grammar.
 */
export function parse(input: string): ExprNode {
  try {
    return ArithParser.parse(input)
  } catch (e) {
    if (e instanceof RDParserException) throw new SyntaxError(e.message)
    throw e
  }
}

// ── Stage 2: validate ────────────────────────────────────────────────────────

/**
 * Stage 2 — check the parse tree for semantic errors.
 *
 * @param tree - Parse tree returned by {@link parse}.
 * @returns `{ ok: true, tree }` when valid, or `{ ok: false, errors }` otherwise.
 */
export function validate(
  tree: ExprNode,
): { ok: true; tree: ExprNode } | { ok: false; errors: ValidationError[] } {
  const errors: ValidationError[] = []
  // TODO: add validation logic
  return errors.length > 0 ? { ok: false, errors } : { ok: true, tree }
}

// ── Stage 3: transform ───────────────────────────────────────────────────────

/**
 * Stage 3 — convert the validated parse tree into a domain {@link ArithResult} object.
 *
 * @param tree - Validated parse tree from {@link validate}.
 * @returns The domain object.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function transform(tree: ExprNode): ArithResult {
  return evalExpr(tree) as unknown as ArithResult
}

// ── Combinator ───────────────────────────────────────────────────────────────

/**
 * Parse, validate, and transform `input` in one call.
 *
 * @param input - Source string to load.
 * @returns The domain object.
 * @throws {SyntaxError} If `input` does not match the grammar.
 * @throws {AggregateError} If `input` fails semantic validation.
 */
export function loadArith(input: string): ArithResult {
  const tree   = parse(input)
  const result = validate(tree)
  if (!result.ok) throw new AggregateError(result.errors, `invalid Arith: "${input}"`)
  return transform(result.tree)
}

// ── Private eval functions ───────────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalExpr(node: ExprNode): unknown {
  // node.wsp0: WspNode
  // node.term: TermNode
  // node.item2: { wsp0: WspNode; item1: string; wsp1: WspNode; term: TermNode }[]
  // node.wsp1: WspNode
  throw new Error('not implemented')
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalTerm(node: TermNode): unknown {
  // node.factor: FactorNode
  // node.item1: { wsp0: WspNode; item1: string; wsp1: WspNode; factor: FactorNode }[]
  throw new Error('not implemented')
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalFactor(node: FactorNode): unknown {
  // node.item0: { item0: string; expr: ExprNode; item2: string } | NumberNode
  throw new Error('not implemented')
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalNumber(node: NumberNode): unknown {
  // node.digit: DigitNode
  // node.item1: DigitNode[]
  throw new Error('not implemented')
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalDigit(node: DigitNode): unknown {
  // node.item0: string
  throw new Error('not implemented')
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalWsp(node: WspNode): unknown {
  // node.item0: string[]
  throw new Error('not implemented')
}
