// Facade + interpreter scaffold generated by rdp-gen — this file is not regenerated; edit freely.
// Steps: 1) define ArithResult constructor fields  2) fill in eval functions
//        3) implement static from() using the eval results  4) remove eslint-disable-next-line comments

import {
  ArithParser,
  type ExprNode,
  type TermNode,
  type FactorNode,
  type NumberNode,
  type DigitNode,
  type WspNode,
} from './ArithParser.js'
import { RDParserException } from '@configuredthings/rdp.js'

// ── Domain type ──────────────────────────────────────────────────────────────

/**
 * Domain representation of a successfully parsed input.
 *
 * Replace the constructor stub with the fields that make sense for your domain.
 * The private eval functions below produce the raw values; `from()` assembles them.
 */
export class ArithResult {
  // TODO: define constructor fields
  constructor() {}

  /**
   * Build a {@link ArithResult} from the raw parse tree.
   *
   * Call the private eval functions to extract values, then construct.
   */
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  static from(tree: ExprNode): ArithResult {
    throw new Error('not implemented')
  }
}

/**
 * Thrown by {@link parseArith} when `input` does not match the grammar.
 */
export class ArithError extends Error {
  constructor(input: string) {
    super(`invalid input: "${input}"`)
    this.name = 'ArithError'
  }
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Parse `input` and return a domain {@link ArithResult} object.
 *
 * @param input - Source string to parse.
 * @returns A {@link ArithResult} representing the parsed input.
 * @throws {@link ArithError} If `input` does not match the grammar.
 */
export function parseArith(input: string): ArithResult {
  let tree: ExprNode
  try {
    tree = ArithParser.parse(input)
  } catch (e) {
    if (e instanceof RDParserException) throw new ArithError(input)
    throw e
  }
  return ArithResult.from(tree)
}

// ── Private ──────────────────────────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalExpr(node: ExprNode): unknown {
  // node.wsp0: WspNode
  // node.term: TermNode
  // node.item2: { wsp0: WspNode; item1: string; wsp1: WspNode; term: TermNode }[]
  // node.wsp1: WspNode
  throw new Error('not implemented')
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalTerm(node: TermNode): unknown {
  // node.factor: FactorNode
  // node.item1: { wsp0: WspNode; item1: string; wsp1: WspNode; factor: FactorNode }[]
  throw new Error('not implemented')
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalFactor(node: FactorNode): unknown {
  // node.item0: { item0: string; expr: ExprNode; item2: string } | NumberNode
  throw new Error('not implemented')
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalNumber(node: NumberNode): unknown {
  // node.digit: DigitNode
  // node.item1: DigitNode[]
  throw new Error('not implemented')
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalDigit(node: DigitNode): unknown {
  // node.item0: string
  throw new Error('not implemented')
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function evalWsp(node: WspNode): unknown {
  // node.item0: string[]
  throw new Error('not implemented')
}
