import { generateParser } from '../../generator/codegen.js'
import { RDParserException } from '../../exception.js'

describe('generateParser', () => {
  it('returns a string containing the class declaration', () => {
    const output = generateParser(`Greeting = 'hello';`, { parserName: 'GreetingParser' })
    expect(output).toContain('class GreetingParser')
  })

  it('uses RDParser as the base class by default', () => {
    const output = generateParser(`Rule = 'x';`)
    expect(output).toContain('extends RDParser')
  })

  it('uses ObservableRDParser when observable is true', () => {
    const output = generateParser(`Rule = 'x';`, { observable: true })
    expect(output).toContain('extends ObservableRDParser')
  })

  it('emits a private constructor', () => {
    const output = generateParser(`Rule = 'x';`)
    expect(output).toContain('private constructor(source: DataView) { super(source) }')
  })

  it('emits a static parse method', () => {
    const output = generateParser(`Rule = 'x';`)
    expect(output).toContain('static parse(input: string)')
    expect(output).toContain('new TextEncoder().encode(input)')
  })

  it('observable: imports ParseObserver and accepts it as second arg to static parse', () => {
    const output = generateParser(`Rule = 'x';`, { observable: true })
    expect(output).toContain('type ParseObserver')
    expect(output).toContain('static parse(input: string, observer?: ParseObserver)')
  })

  it('includes the generated file header comment', () => {
    const output = generateParser(`Rule = 'x';`)
    expect(output).toContain('generated by rdp-gen')
  })

  it('emits a method for each production rule', () => {
    const output = generateParser(`A = 'x';\nB = 'y';`)
    expect(output).toContain('#parse_a()')
    expect(output).toContain('#parse_b()')
  })

  it('converts hyphenated and underscored rule names to camelCase method names', () => {
    const output = generateParser(`my-rule = 'x';\nother_rule = 'y';`, { format: 'ebnf' })
    expect(output).toContain('#parse_myRule()')
    expect(output).toContain('#parse_otherRule()')
  })

  it('handles ABNF format', () => {
    const output = generateParser(`rule = "hello"`, { format: 'abnf', parserName: 'ABNFParser' })
    expect(output).toContain('class ABNFParser')
  })

  it('throws on a left-recursive grammar', () => {
    expect(() => generateParser(`A = A;`)).toThrow(RDParserException)
  })

  it('emits core rule helpers when ABNF uses them', () => {
    const output = generateParser(`rule = ALPHA`, { format: 'abnf' })
    expect(output).toContain('#alpha()')
  })
})

describe('generateParser — grammar construct coverage', () => {
  // ── Atoms ──────────────────────────────────────────────────────────────────

  it('emits readChar for a single-char terminal', () => {
    const output = generateParser(`Rule = 'x';`)
    expect(output).toContain('readChar')
  })

  it('emits matchChar for each character of a multi-char terminal', () => {
    const output = generateParser(`Rule = 'hi';`)
    expect(output).toContain('matchChar')
    expect(output).toContain('"hi"')
  })

  it('emits a non-terminal method call for rule references', () => {
    // nonTerminal case in emitCapture
    const output = generateParser(`A = B;\nB = 'x';`)
    expect(output).toContain('#parse_b()')
  })

  it('emits readCharRange for an ABNF character range', () => {
    // charValue with range
    const output = generateParser(`rule = %x41-5A`, { format: 'abnf' })
    expect(output).toContain('readCharRange')
  })

  it('emits readChar for a single ABNF codepoint', () => {
    // charValue single codepoint
    const output = generateParser(`rule = %x41`, { format: 'abnf' })
    expect(output).toContain('readChar(0x41)')
  })

  it('emits found/alt labels for multiple ABNF codepoints', () => {
    // charValue with multiple codepoints (%x41.42)
    const output = generateParser(`rule = %x41.42`, { format: 'abnf' })
    expect(output).toContain('found')
    expect(output).toContain('alt')
  })

  // ── Composites ─────────────────────────────────────────────────────────────

  it('emits found/alt labels for alternation', () => {
    // alternation case in emitCapture
    const output = generateParser(`Rule = 'a' | 'b';`)
    expect(output).toContain('found')
    expect(output).toContain('alt')
  })

  it('emits an opt label and null initialiser for optional', () => {
    // optional case in emitCapture
    const output = generateParser(`Rule = ['a'];`)
    expect(output).toContain('opt')
    expect(output).toContain('null')
  })

  it('emits a loop label and while(true) for zeroOrMore', () => {
    // zeroOrMore case in emitCapture
    const output = generateParser(`Rule = {'a'};`)
    expect(output).toContain('loop')
    expect(output).toContain('while (true)')
  })

  it('emits a loop label for oneOrMore (via sequence + zeroOrMore)', () => {
    // oneOrMore expressed as item, {item}
    const output = generateParser(`Rule = 'a', {'a'};`)
    expect(output).toContain('loop')
  })

  it('emits a rep label and count variable for ABNF bounded repetition', () => {
    // repetition case in emitCapture
    const output = generateParser(`rule = 2*4"a"`, { format: 'abnf' })
    expect(output).toContain('rep')
    expect(output).toContain('count')
  })

  it('emits an anonymous object for a sequence sub-expression inside alternation', () => {
    // sequence case in emitCapture (sequence as a sub-expression, not at rule level)
    const output = generateParser(`Rule = ('a', 'b') | 'c';`)
    // The inline sequence produces an object with item0/item1 fields
    expect(output).toContain('item0')
    expect(output).toContain('item1')
  })

  // ── Observable mode ────────────────────────────────────────────────────────

  it('emits notifyEnter/notifyExit and #failNotify in observable mode', () => {
    const output = generateParser(`Rule = 'a' | 'b';`, { observable: true })
    expect(output).toContain('notifyEnter')
    expect(output).toContain('notifyExit')
    expect(output).toContain('#failNotify')
  })

  // ── Core rule collection in nested contexts ────────────────────────────────

  it('emits core rule helpers when used inside zeroOrMore', () => {
    // collectCoreRulesInBody for zeroOrMore/oneOrMore/optional/repetition
    const output = generateParser(`rule = *ALPHA`, { format: 'abnf' })
    expect(output).toContain('#alpha()')
  })

  it('emits core rule helpers when used inside alternation and sequence', () => {
    // collectCoreRulesInBody for alternation and sequence
    const output = generateParser(`rule = ALPHA / DIGIT`, { format: 'abnf' })
    expect(output).toContain('#alpha()')
    expect(output).toContain('#digit()')
  })

  it('emits core rule helpers when used inside optional', () => {
    const output = generateParser(`rule = [ALPHA]`, { format: 'abnf' })
    expect(output).toContain('#alpha()')
  })

  it('emits core rule helpers when used inside oneOrMore', () => {
    const output = generateParser(`rule = 1*DIGIT`, { format: 'abnf' })
    expect(output).toContain('#digit()')
  })

  it('emits core rule helpers when used inside bounded repetition', () => {
    const output = generateParser(`rule = 2*4ALPHA`, { format: 'abnf' })
    expect(output).toContain('#alpha()')
  })

  it('emits separate captured fields for a top-level sequence rule body', () => {
    // Exercises body.kind === 'sequence' branch in emitMethod
    const output = generateParser(`Rule = 'a', 'b';`)
    expect(output).toContain('item0:')
    expect(output).toContain('item1:')
  })

  it('emits while(true) for a repetition with unbounded max', () => {
    // body.max === null → maxCond = 'true'
    const output = generateParser(`rule = 2*"a"`, { format: 'abnf' })
    expect(output).toContain('while (true)')
  })

  it('passes caseSensitiveStrings through to the ABNF parser', () => {
    // Exercises the options.caseSensitiveStrings !== undefined spread in generateParser
    const output = generateParser(`rule = "Hello"`, { format: 'abnf', caseSensitiveStrings: true })
    // 'H' (0x48) should appear as a literal character match, not lowercased
    expect(output).toContain('0x48')
  })
})
