import ts from 'typescript'
import path from 'path'
import { fileURLToPath } from 'url'
import { generateParser } from '../../generator/codegen.js'
import { RDParserException } from '../../exception.js'
import { compileAndImport, nav } from '../../__testUtils__/generator-runtime.js'

// ── TypeScript strict-typing helper ──────────────────────────────────────────

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../')
const VIRTUAL_FILE = '__generated_virtual__.ts'

/**
 * Type-check a generated TypeScript source string using the TypeScript compiler
 * API under the same strict settings the generated file header requires.
 * Returns an array of human-readable diagnostic messages (empty = no errors).
 */
function typeCheck(source: string): string[] {
  const compilerOptions: ts.CompilerOptions = {
    target: ts.ScriptTarget.ES2022,
    strict: true,
    noUncheckedIndexedAccess: true,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    module: ts.ModuleKind.ES2022,
    noEmit: true,
    skipLibCheck: true, // only check our generated file, not the rdp.js library itself
    paths: {
      '@configuredthings/rdp.js': [path.join(ROOT, 'dist/esm/index.d.ts')],
      '@configuredthings/rdp.js/observable': [path.join(ROOT, 'dist/esm/observable/index.d.ts')],
    },
  }

  const defaultHost = ts.createCompilerHost(compilerOptions)
  const host: ts.CompilerHost = {
    ...defaultHost,
    getSourceFile(fileName, langVer, onError) {
      if (fileName === VIRTUAL_FILE) return ts.createSourceFile(fileName, source, langVer)
      return defaultHost.getSourceFile(fileName, langVer, onError)
    },
    fileExists(fileName) {
      return fileName === VIRTUAL_FILE || defaultHost.fileExists(fileName)
    },
    readFile(fileName) {
      return fileName === VIRTUAL_FILE ? source : defaultHost.readFile(fileName)
    },
  }

  const program = ts.createProgram([VIRTUAL_FILE], compilerOptions, host)
  const diags = ts.getPreEmitDiagnostics(program, program.getSourceFile(VIRTUAL_FILE))
  return [...diags].map((d) => ts.flattenDiagnosticMessageText(d.messageText, '\n'))
}

describe('generateParser', () => {
  it('returns a string containing the class declaration', () => {
    const output = generateParser(`Greeting = 'hello';`, { parserName: 'GreetingParser' })
    expect(output).toContain('class GreetingParser')
  })

  it('uses RDParser as the base class by default', () => {
    const output = generateParser(`Rule = 'x';`)
    expect(output).toContain('extends RDParser')
  })

  it('uses ObservableRDParser when observable is true', () => {
    const output = generateParser(`Rule = 'x';`, { observable: true })
    expect(output).toContain('extends ObservableRDParser')
  })

  it('emits a private constructor', () => {
    const output = generateParser(`Rule = 'x';`)
    expect(output).toContain('private constructor(source: DataView) {')
  })

  it('emits a static parse method', () => {
    const output = generateParser(`Rule = 'x';`)
    expect(output).toContain('static parse(input: string)')
    expect(output).toContain('new TextEncoder().encode(input)')
  })

  it('observable: imports ParseObserver and accepts it as second arg to static parse', () => {
    const output = generateParser(`Rule = 'x';`, { observable: true })
    expect(output).toContain('type ParseObserver')
    expect(output).toContain('static parse(input: string, observer?: ParseObserver)')
  })

  it('includes the generated file header comment', () => {
    const output = generateParser(`Rule = 'x';`)
    expect(output).toContain('generated by rdp-gen')
  })

  it('emits a method for each production rule', () => {
    const output = generateParser(`A = 'x';\nB = 'y';`)
    expect(output).toContain('#parse_a()')
    expect(output).toContain('#parse_b()')
  })

  it('converts hyphenated and underscored rule names to camelCase method names', () => {
    const output = generateParser(`my-rule = 'x';\nother_rule = 'y';`, { format: 'ebnf' })
    expect(output).toContain('#parse_myRule()')
    expect(output).toContain('#parse_otherRule()')
  })

  it('handles ABNF format', () => {
    const output = generateParser(`rule = "hello"`, { format: 'abnf', parserName: 'ABNFParser' })
    expect(output).toContain('class ABNFParser')
  })

  it('throws on a left-recursive grammar', () => {
    expect(() => generateParser(`A = A;`)).toThrow(RDParserException)
  })

  it('emits core rule helpers when ABNF uses them', () => {
    const output = generateParser(`rule = ALPHA`, { format: 'abnf' })
    expect(output).toContain('#alpha()')
  })
})

describe('generateParser — grammar construct coverage', () => {
  // ── Atoms ──────────────────────────────────────────────────────────────────

  it('emits readChar for a single-char terminal', () => {
    const output = generateParser(`Rule = 'x';`)
    expect(output).toContain('readChar')
  })

  it('emits matchChar for each character of a multi-char terminal', () => {
    const output = generateParser(`Rule = 'hi';`)
    expect(output).toContain('matchChar')
    expect(output).toContain('"hi"')
  })

  it('emits a non-terminal method call for rule references', () => {
    // nonTerminal case in emitCapture
    const output = generateParser(`A = B;\nB = 'x';`)
    expect(output).toContain('#parse_b()')
  })

  it('emits readCharRange for an ABNF character range', () => {
    // charValue with range
    const output = generateParser(`rule = %x41-5A`, { format: 'abnf' })
    expect(output).toContain('readCharRange')
  })

  it('emits readChar for a single ABNF codepoint', () => {
    // charValue single codepoint
    const output = generateParser(`rule = %x41`, { format: 'abnf' })
    expect(output).toContain('readChar(0x41)')
  })

  it('emits found/alt labels for multiple ABNF codepoints', () => {
    // charValue with multiple codepoints (%x41.42)
    const output = generateParser(`rule = %x41.42`, { format: 'abnf' })
    expect(output).toContain('found')
    expect(output).toContain('alt')
  })

  // ── Composites ─────────────────────────────────────────────────────────────

  it('emits found/alt labels for alternation', () => {
    // alternation case in emitCapture
    const output = generateParser(`Rule = 'a' | 'b';`)
    expect(output).toContain('found')
    expect(output).toContain('alt')
  })

  it('emits an opt label and null initialiser for optional', () => {
    // optional case in emitCapture
    const output = generateParser(`Rule = ['a'];`)
    expect(output).toContain('opt')
    expect(output).toContain('null')
  })

  it('emits a loop label and while(true) for zeroOrMore', () => {
    // zeroOrMore case in emitCapture
    const output = generateParser(`Rule = {'a'};`)
    expect(output).toContain('loop')
    expect(output).toContain('while (true)')
  })

  it('emits a loop label for oneOrMore (via sequence + zeroOrMore)', () => {
    // oneOrMore expressed as item, {item}
    const output = generateParser(`Rule = 'a', {'a'};`)
    expect(output).toContain('loop')
  })

  it('emits a rep label and count variable for ABNF bounded repetition', () => {
    // repetition case in emitCapture
    const output = generateParser(`rule = 2*4"a"`, { format: 'abnf' })
    expect(output).toContain('rep')
    expect(output).toContain('count')
  })

  it('emits an anonymous object for a sequence sub-expression inside alternation', () => {
    // sequence case in emitCapture (sequence as a sub-expression, not at rule level)
    const output = generateParser(`Rule = ('a', 'b') | 'c';`)
    // The inline sequence produces an object with item0/item1 fields
    expect(output).toContain('item0')
    expect(output).toContain('item1')
  })

  // ── Observable mode ────────────────────────────────────────────────────────

  it('emits notifyEnter/notifyExit and #failNotify in observable mode', () => {
    const output = generateParser(`Rule = 'a' | 'b';`, { observable: true })
    expect(output).toContain('notifyEnter')
    expect(output).toContain('notifyExit')
    expect(output).toContain('#failNotify')
  })

  // ── Core rule collection in nested contexts ────────────────────────────────

  it('emits core rule helpers when used inside zeroOrMore', () => {
    // collectCoreRulesInBody for zeroOrMore/oneOrMore/optional/repetition
    const output = generateParser(`rule = *ALPHA`, { format: 'abnf' })
    expect(output).toContain('#alpha()')
  })

  it('emits core rule helpers when used inside alternation and sequence', () => {
    // collectCoreRulesInBody for alternation and sequence
    const output = generateParser(`rule = ALPHA / DIGIT`, { format: 'abnf' })
    expect(output).toContain('#alpha()')
    expect(output).toContain('#digit()')
  })

  it('emits core rule helpers when used inside optional', () => {
    const output = generateParser(`rule = [ALPHA]`, { format: 'abnf' })
    expect(output).toContain('#alpha()')
  })

  it('emits core rule helpers when used inside oneOrMore', () => {
    const output = generateParser(`rule = 1*DIGIT`, { format: 'abnf' })
    expect(output).toContain('#digit()')
  })

  it('emits core rule helpers when used inside bounded repetition', () => {
    const output = generateParser(`rule = 2*4ALPHA`, { format: 'abnf' })
    expect(output).toContain('#alpha()')
  })

  it('emits separate captured fields for a top-level sequence rule body', () => {
    // Exercises body.kind === 'sequence' branch in emitMethod
    const output = generateParser(`Rule = 'a', 'b';`)
    expect(output).toContain('item0:')
    expect(output).toContain('item1:')
  })

  it('emits while(true) for a repetition with unbounded max', () => {
    // body.max === null → maxCond = 'true'
    const output = generateParser(`rule = 2*"a"`, { format: 'abnf' })
    expect(output).toContain('while (true)')
  })

  it('passes caseSensitiveStrings through to the ABNF parser', () => {
    // Exercises the options.caseSensitiveStrings !== undefined spread in generateParser
    const output = generateParser(`rule = "Hello"`, { format: 'abnf', caseSensitiveStrings: true })
    // 'H' (0x48) should appear as a literal character match, not lowercased
    expect(output).toContain('0x48')
  })

  // ── Regression: repeated alternation of mixed types ───────────────────────
  // Bug: `*(A / B)` was emitting `A | B[]` (parsed by TS as `A | (B[])`) instead
  // of `(A | B)[]` in both variable declarations and exported type aliases.

  it('emits (A | B)[] not A | B[] for zeroOrMore of a mixed-type alternation', () => {
    const output = generateParser(`rule = {'a' | foo};\nfoo = 'b';`)
    expect(output).toContain('(string | FooNode)[]')
    expect(output).not.toContain('string | FooNode[]')
  })

  it('emits (A | B)[] not A | B[] for oneOrMore of a mixed-type alternation', () => {
    const output = generateParser(`rule = 'a' | foo, {'a' | foo};\nfoo = 'b';`)
    expect(output).toContain('(string | FooNode)[]')
    expect(output).not.toContain('string | FooNode[]')
  })

  it('emits (A | B)[] not A | B[] for ABNF bounded repetition of a mixed-type alternation', () => {
    const output = generateParser(`rule = 1*3("a" / foo)\nfoo = "b"`, { format: 'abnf' })
    expect(output).toContain('(string | FooNode)[]')
    expect(output).not.toContain('string | FooNode[]')
  })
})

describe('generateParser — emitted code passes strict TypeScript type-checking', () => {
  it('simple terminal rule compiles cleanly', () => {
    const output = generateParser(`Rule = 'hello';`)
    expect(typeCheck(output)).toEqual([])
  })

  it('sequence rule compiles cleanly', () => {
    const output = generateParser(`Root = 'a', 'b', 'c';`)
    expect(typeCheck(output)).toEqual([])
  })

  it('alternation with mixed node and string types compiles cleanly', () => {
    // Exercises the (A | B)[] wrapping and definite-assignment assertions
    const output = generateParser(`root = {'a' | item};\nitem = 'x';`)
    expect(typeCheck(output)).toEqual([])
  })

  it('optional and zeroOrMore constructs compile cleanly', () => {
    const output = generateParser(`root = ['opt'], {'rep'};`)
    expect(typeCheck(output)).toEqual([])
  })

  it('non-terminal references compile cleanly', () => {
    const output = generateParser(
      `root = greeting, ' ', name;\ngreeting = 'hello';\nname = 'world';`,
    )
    expect(typeCheck(output)).toEqual([])
  })

  it('observable mode compiles cleanly', () => {
    const output = generateParser(`root = 'a' | item;\nitem = 'b';`, { observable: true })
    expect(typeCheck(output)).toEqual([])
  })

  it('ABNF grammar with core rules compiles cleanly', () => {
    const output = generateParser(`word = 1*ALPHA\nalpha = ALPHA`, { format: 'abnf' })
    expect(typeCheck(output)).toEqual([])
  })

  it('ABNF bounded repetition compiles cleanly', () => {
    const output = generateParser(`rule = 2*4"a"`, { format: 'abnf' })
    expect(typeCheck(output)).toEqual([])
  })

  it('walker: true emits childNodes and the output compiles cleanly', () => {
    const output = generateParser(
      `Expr = Term, {('+' | '-'), Term};\nTerm = Factor, {('*' | '/'), Factor};\nFactor = '(', Expr, ')' | Number;\nNumber = Digit, {Digit};\nDigit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';`,
      { parserName: 'ExprParser', walker: true },
    )
    expect(output).toContain('function childNodes')
    expect(typeCheck(output)).toEqual([])
  })
})

// ── Runtime correctness ──────────────────────────────────────────────────────
//
// The grammar below covers: sequence, alternation, zeroOrMore, optional (via
// the '(' Expr ')' branch), and non-terminal references — enough surface area
// to catch structural bugs in any generated parser or walker.

const EXPR_GRAMMAR = `Expr = Term, {('+' | '-'), Term};\nTerm = Factor, {('*' | '/'), Factor};\nFactor = '(', Expr, ')' | Number;\nNumber = Digit, {Digit};\nDigit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';`

// ── Generated parser — runtime correctness ───────────────────────────────────

describe('generated parser — runtime correctness', () => {
  let ExprParser!: { parse(s: string): unknown }

  beforeAll(async () => {
    const source = generateParser(EXPR_GRAMMAR, { parserName: 'ExprParser', walker: true })
    const { ExprParser: Ep } = await compileAndImport(source)
    ExprParser = Ep as { parse(s: string): unknown }
  })

  it('root node has kind "Expr"', () => {
    expect(nav(ExprParser.parse('1'), 'kind')).toBe('Expr')
  })

  it('parses a single digit — DigitNode.item0 holds the matched character', () => {
    // Expr → Term → Factor.item0 (NumberNode) → Number.digit (DigitNode) → .item0
    expect(nav(ExprParser.parse('9'), 'term', 'factor', 'item0', 'digit', 'item0')).toBe('9')
  })

  it('parses a two-digit number — NumberNode.item1 holds subsequent DigitNodes', () => {
    // Number = Digit, {Digit}  →  { digit: DigitNode; item1: DigitNode[] }
    const number = nav(ExprParser.parse('42'), 'term', 'factor', 'item0')
    expect(nav(number, 'kind')).toBe('Number')
    expect(nav(number, 'digit', 'item0')).toBe('4')
    expect(nav(number, 'item1', '0', 'item0')).toBe('2')
  })

  it('parses "1+2" — ExprNode.item1 records the operator and right-hand Term', () => {
    // Expr = Term, {('+' | '-'), Term}  →  item1: { item0: string; term: TermNode }[]
    const pairs = nav(ExprParser.parse('1+2'), 'item1') as unknown[]
    expect(pairs).toHaveLength(1)
    expect(nav(pairs[0], 'item0')).toBe('+')
    expect(nav(pairs[0], 'term', 'kind')).toBe('Term')
  })

  it('throws on a non-digit character', () => {
    expect(() => ExprParser.parse('x')).toThrow()
  })

  it('throws on empty input', () => {
    expect(() => ExprParser.parse('')).toThrow()
  })

  it('throws on a trailing operator with no right-hand operand', () => {
    expect(() => ExprParser.parse('1+')).toThrow()
  })
})

// ── Generated walker — runtime correctness ───────────────────────────────────

describe('generated walker — runtime correctness', () => {
  let ExprParser!: { parse(s: string): { kind: string } }
  let childNodes!: (n: unknown) => { kind: string }[]

  beforeAll(async () => {
    const source = generateParser(EXPR_GRAMMAR, { parserName: 'ExprParser', walker: true })
    const { ExprParser: Ep, childNodes: cn } = await compileAndImport(source)
    ExprParser = Ep as { parse(s: string): { kind: string } }
    childNodes = cn as (n: unknown) => { kind: string }[]
  })

  it('childNodes of the Expr root for "1+2" returns both Term children', () => {
    const children = childNodes(ExprParser.parse('1+2'))
    expect(children).toHaveLength(2)
    expect(children[0]?.kind).toBe('Term')
    expect(children[1]?.kind).toBe('Term')
  })

  it('childNodes of a Digit node (leaf) returns []', () => {
    // Walk down: expr → term → factor → number → digit
    const tree = ExprParser.parse('1')
    const [term] = childNodes(tree)
    const [factor] = childNodes(term)
    const [number] = childNodes(factor)
    const [digit] = childNodes(number)
    expect(childNodes(digit)).toHaveLength(0)
  })

  it('BFS via childNodes visits every non-terminal node in "1+2"', () => {
    // "1+2" → Expr → Term(1), Term(2) → Factor×2 → Number×2 → Digit×2
    const visited: string[] = []
    const queue: { kind: string }[] = [ExprParser.parse('1+2')]
    while (queue.length > 0) {
      const node = queue.shift()
      if (node === undefined) break
      visited.push(node.kind)
      queue.push(...childNodes(node))
    }
    expect(visited).toEqual([
      'Expr',
      'Term',
      'Term',
      'Factor',
      'Factor',
      'Number',
      'Number',
      'Digit',
      'Digit',
    ])
  })
})
