import { generateTypes, typeForBody } from '../../generator/type-gen.js'
import type { GrammarAST, RuleBody } from '../../generator/ast.js'

const simpleAst: GrammarAST = {
  rules: [{ name: 'greeting', body: { kind: 'terminal', value: 'hello' } }],
}

describe('generateTypes', () => {
  it('emits a type alias for each rule', () => {
    const output = generateTypes(simpleAst)
    expect(output).toContain('GreetingNode')
  })

  it('emits the root ParseTree union', () => {
    const output = generateTypes(simpleAst)
    expect(output).toContain('type ParseTree')
  })

  it('uses the custom treeName when provided', () => {
    const output = generateTypes(simpleAst, { treeName: 'MyTree' })
    expect(output).toContain('type MyTree')
  })

  it('includes the generated file header comment', () => {
    const output = generateTypes(simpleAst)
    expect(output).toContain('generated by rdp-gen')
  })

  it('emits a kind discriminant for each node type', () => {
    const output = generateTypes(simpleAst)
    expect(output).toContain("kind: 'greeting'")
  })

  it('flattens top-level sequence bodies into separate named fields', () => {
    const ast: GrammarAST = {
      rules: [
        {
          name: 'pair',
          body: {
            kind: 'sequence',
            items: [
              { kind: 'terminal', value: 'a' },
              { kind: 'terminal', value: 'b' },
            ],
          },
        },
      ],
    }
    const output = generateTypes(ast)
    expect(output).toContain('item0: string')
    expect(output).toContain('item1: string')
  })
})

describe('typeForBody', () => {
  it('returns string for a terminal', () => {
    expect(typeForBody({ kind: 'terminal', value: 'x' })).toBe('string')
  })

  it('returns string for a coreRule', () => {
    expect(typeForBody({ kind: 'coreRule', name: 'ALPHA' })).toBe('string')
  })

  it('returns string for a charValue', () => {
    const body: RuleBody = { kind: 'charValue', encoding: 'x', codepoints: [0x41] }
    expect(typeForBody(body)).toBe('string')
  })

  it('returns XxxNode for a nonTerminal', () => {
    expect(typeForBody({ kind: 'nonTerminal', name: 'expr' })).toBe('ExprNode')
  })

  it('handles hyphenated nonTerminal names with PascalCase', () => {
    expect(typeForBody({ kind: 'nonTerminal', name: 'my-rule' })).toBe('MyRuleNode')
  })

  it('returns an anonymous object type for a sequence', () => {
    const body: RuleBody = {
      kind: 'sequence',
      items: [
        { kind: 'terminal', value: 'a' },
        { kind: 'nonTerminal', name: 'expr' },
      ],
    }
    const result = typeForBody(body)
    expect(result).toContain('item0: string')
    expect(result).toContain('item1: ExprNode')
  })

  it('returns a union type for an alternation', () => {
    const body: RuleBody = {
      kind: 'alternation',
      items: [
        { kind: 'terminal', value: 'a' },
        { kind: 'nonTerminal', name: 'foo' },
      ],
    }
    const result = typeForBody(body)
    expect(result).toContain('string')
    expect(result).toContain('FooNode')
  })

  it('deduplicates repeated types in an alternation union', () => {
    const body: RuleBody = {
      kind: 'alternation',
      items: [
        { kind: 'terminal', value: 'a' },
        { kind: 'terminal', value: 'b' },
      ],
    }
    // both alternatives have type 'string' — should deduplicate
    expect(typeForBody(body)).toBe('string')
  })

  it('returns T | null for optional', () => {
    const body: RuleBody = { kind: 'optional', item: { kind: 'terminal', value: 'x' } }
    expect(typeForBody(body)).toBe('string | null')
  })

  it('returns T[] for zeroOrMore', () => {
    const body: RuleBody = { kind: 'zeroOrMore', item: { kind: 'terminal', value: 'x' } }
    expect(typeForBody(body)).toBe('string[]')
  })

  it('returns T[] for oneOrMore', () => {
    const body: RuleBody = { kind: 'oneOrMore', item: { kind: 'terminal', value: 'x' } }
    expect(typeForBody(body)).toBe('string[]')
  })

  it('returns T[] for repetition', () => {
    const body: RuleBody = {
      kind: 'repetition',
      min: 2,
      max: 4,
      item: { kind: 'terminal', value: 'x' },
    }
    expect(typeForBody(body)).toBe('string[]')
  })
})
