import { generateTypes, generateWalker, typeForBody } from '../../generator/type-gen.js'
import type { GrammarAST, RuleBody } from '../../generator/ast.js'

const simpleAst: GrammarAST = {
  rules: [{ name: 'greeting', body: { kind: 'terminal', value: 'hello' } }],
}

describe('generateTypes', () => {
  it('emits a type alias for each rule', () => {
    const output = generateTypes(simpleAst)
    expect(output).toContain('GreetingNode')
  })

  it('emits the root ParseTree union', () => {
    const output = generateTypes(simpleAst)
    expect(output).toContain('type ParseTree')
  })

  it('uses the custom treeName when provided', () => {
    const output = generateTypes(simpleAst, { treeName: 'MyTree' })
    expect(output).toContain('type MyTree')
  })

  it('includes the generated file header comment', () => {
    const output = generateTypes(simpleAst)
    expect(output).toContain('generated by rdp-gen')
  })

  it('emits a kind discriminant for each node type', () => {
    const output = generateTypes(simpleAst)
    expect(output).toContain("kind: 'greeting'")
  })

  it('flattens top-level sequence bodies into separate named fields', () => {
    const ast: GrammarAST = {
      rules: [
        {
          name: 'pair',
          body: {
            kind: 'sequence',
            items: [
              { kind: 'terminal', value: 'a' },
              { kind: 'terminal', value: 'b' },
            ],
          },
        },
      ],
    }
    const output = generateTypes(ast)
    expect(output).toContain('item0: string')
    expect(output).toContain('item1: string')
  })
})

describe('typeForBody', () => {
  it('returns string for a terminal', () => {
    expect(typeForBody({ kind: 'terminal', value: 'x' })).toBe('string')
  })

  it('returns string for a coreRule', () => {
    expect(typeForBody({ kind: 'coreRule', name: 'ALPHA' })).toBe('string')
  })

  it('returns string for a charValue', () => {
    const body: RuleBody = { kind: 'charValue', encoding: 'x', codepoints: [0x41] }
    expect(typeForBody(body)).toBe('string')
  })

  it('returns XxxNode for a nonTerminal', () => {
    expect(typeForBody({ kind: 'nonTerminal', name: 'expr' })).toBe('ExprNode')
  })

  it('handles hyphenated nonTerminal names with PascalCase', () => {
    expect(typeForBody({ kind: 'nonTerminal', name: 'my-rule' })).toBe('MyRuleNode')
  })

  it('returns an anonymous object type for a sequence', () => {
    const body: RuleBody = {
      kind: 'sequence',
      items: [
        { kind: 'terminal', value: 'a' },
        { kind: 'nonTerminal', name: 'expr' },
      ],
    }
    const result = typeForBody(body)
    expect(result).toContain('item0: string')
    expect(result).toContain('expr: ExprNode')
  })

  it('returns a union type for an alternation', () => {
    const body: RuleBody = {
      kind: 'alternation',
      items: [
        { kind: 'terminal', value: 'a' },
        { kind: 'nonTerminal', name: 'foo' },
      ],
    }
    const result = typeForBody(body)
    expect(result).toContain('string')
    expect(result).toContain('FooNode')
  })

  it('deduplicates repeated types in an alternation union', () => {
    const body: RuleBody = {
      kind: 'alternation',
      items: [
        { kind: 'terminal', value: 'a' },
        { kind: 'terminal', value: 'b' },
      ],
    }
    // both alternatives have type 'string' — should deduplicate
    expect(typeForBody(body)).toBe('string')
  })

  it('returns T | null for optional', () => {
    const body: RuleBody = { kind: 'optional', item: { kind: 'terminal', value: 'x' } }
    expect(typeForBody(body)).toBe('string | null')
  })

  it('returns T[] for zeroOrMore', () => {
    const body: RuleBody = { kind: 'zeroOrMore', item: { kind: 'terminal', value: 'x' } }
    expect(typeForBody(body)).toBe('string[]')
  })

  it('returns T[] for oneOrMore', () => {
    const body: RuleBody = { kind: 'oneOrMore', item: { kind: 'terminal', value: 'x' } }
    expect(typeForBody(body)).toBe('string[]')
  })

  it('returns T[] for repetition', () => {
    const body: RuleBody = {
      kind: 'repetition',
      min: 2,
      max: 4,
      item: { kind: 'terminal', value: 'x' },
    }
    expect(typeForBody(body)).toBe('string[]')
  })

  // ── Regression: repeated alternation of mixed types ───────────────────────
  // Bug: `*(A / B)` was emitting `A | B[]` (parsed by TS as `A | (B[])`) instead
  // of `(A | B)[]`. The fix wraps union item types in parentheses.

  const mixedAlt: RuleBody = {
    kind: 'alternation',
    items: [
      { kind: 'terminal', value: 'a' },
      { kind: 'nonTerminal', name: 'foo' },
    ],
  }

  it('wraps union item type in parentheses for zeroOrMore of alternation', () => {
    expect(typeForBody({ kind: 'zeroOrMore', item: mixedAlt })).toBe('(string | FooNode)[]')
  })

  it('wraps union item type in parentheses for oneOrMore of alternation', () => {
    expect(typeForBody({ kind: 'oneOrMore', item: mixedAlt })).toBe('(string | FooNode)[]')
  })

  it('wraps union item type in parentheses for repetition of alternation', () => {
    expect(typeForBody({ kind: 'repetition', min: 0, max: 5, item: mixedAlt })).toBe(
      '(string | FooNode)[]',
    )
  })
})

describe('generateWalker', () => {
  it('emits a childNodes function', () => {
    const output = generateWalker(simpleAst)
    expect(output).toContain('function childNodes')
  })

  it('uses the custom treeName when provided', () => {
    const output = generateWalker(simpleAst, { treeName: 'MyTree' })
    expect(output).toContain('childNodes(node: MyTree): MyTree[]')
  })

  it('emits a leaf case (break, no push) for a rule with no non-terminal fields', () => {
    // greeting = 'hello' — terminal only, no child nodes
    const output = generateWalker(simpleAst)
    expect(output).toContain("case 'greeting': break")
    expect(output).not.toContain('children.push')
  })

  it('emits children.push for a rule with a direct non-terminal field', () => {
    const ast: GrammarAST = {
      rules: [
        { name: 'wrapper', body: { kind: 'nonTerminal', name: 'inner' } },
        { name: 'inner', body: { kind: 'terminal', value: 'x' } },
      ],
    }
    const output = generateWalker(ast)
    expect(output).toContain('children.push(node.inner)')
  })

  it('emits a spread push for a zeroOrMore of non-terminals', () => {
    const ast: GrammarAST = {
      rules: [
        {
          name: 'list',
          body: { kind: 'zeroOrMore', item: { kind: 'nonTerminal', name: 'item' } },
        },
        { name: 'item', body: { kind: 'terminal', value: 'x' } },
      ],
    }
    const output = generateWalker(ast)
    expect(output).toContain('children.push(...node.item0)')
  })

  it('emits a for-of loop for a zeroOrMore of sequences containing non-terminals', () => {
    // Expr = Term, {('+' | '-'), Term} — item1 is an array of sequences
    const ast: GrammarAST = {
      rules: [
        {
          name: 'expr',
          body: {
            kind: 'sequence',
            items: [
              { kind: 'nonTerminal', name: 'term' },
              {
                kind: 'zeroOrMore',
                item: {
                  kind: 'sequence',
                  items: [
                    {
                      kind: 'alternation',
                      items: [
                        { kind: 'terminal', value: '+' },
                        { kind: 'terminal', value: '-' },
                      ],
                    },
                    { kind: 'nonTerminal', name: 'term' },
                  ],
                },
              },
            ],
          },
        },
        { name: 'term', body: { kind: 'terminal', value: 'x' } },
      ],
    }
    const output = generateWalker(ast)
    expect(output).toContain('children.push(node.term)')
    expect(output).toContain('for (const _item0 of node.item1)')
    expect(output).toContain('children.push(_item0.term)')
  })

  it('emits a null-guard for an optional non-terminal field', () => {
    const ast: GrammarAST = {
      rules: [
        {
          name: 'maybe',
          body: { kind: 'optional', item: { kind: 'nonTerminal', name: 'inner' } },
        },
        { name: 'inner', body: { kind: 'terminal', value: 'x' } },
      ],
    }
    const output = generateWalker(ast)
    expect(output).toContain('if (node.item0 !== null) children.push(node.item0)')
  })

  it('emits a typeof guard for an alternation mixing non-terminals and strings', () => {
    // Factor = '(' Expr ')' | Number — item0 is a sequence-or-node union
    const ast: GrammarAST = {
      rules: [
        {
          name: 'factor',
          body: {
            kind: 'alternation',
            items: [
              {
                kind: 'sequence',
                items: [
                  { kind: 'terminal', value: '(' },
                  { kind: 'nonTerminal', name: 'expr' },
                  { kind: 'terminal', value: ')' },
                ],
              },
              { kind: 'nonTerminal', name: 'number' },
            ],
          },
        },
        { name: 'expr', body: { kind: 'terminal', value: 'x' } },
        { name: 'number', body: { kind: 'terminal', value: 'x' } },
      ],
    }
    const output = generateWalker(ast)
    // Should discriminate using 'kind' in check
    expect(output).toContain("'kind' in")
  })
})
