// Walker scaffold generated by rdp-gen — this file is not regenerated; edit freely.
// --walker adds childNodes() to the parser file; this scaffold shows how to use it.
// Once you uncomment the visitor below, remove the eslint-disable-next-line comments.

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { ArithParser, childNodes, type ArithTree } from './ArithParser.js'
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { visit, type Visitor } from '@configuredthings/rdp.js'

export function walk(root: ArithTree, fn: (node: ArithTree) => void): void {
  fn(root)
  for (const child of childNodes(root)) walk(child, fn)
}

// Add handlers for the node kinds you care about.
// Use Required<Visitor<ArithTree>> to enforce that every kind is handled.
//
// const visitor: Visitor<ArithTree> = {
//   'Expr': (node) => { /* ... */ },
//   'Term': (node) => { /* ... */ },
//   'Factor': (node) => { /* ... */ },
//   'Number': (node) => { /* ... */ },
//   'Digit': (node) => { /* ... */ },
//   'wsp': (node) => { /* ... */ },
// }
//
// walk(ArithParser.parse(input), (node) => visit(node, visitor))
