// Evaluator scaffold generated by rdp-gen — this file is not regenerated; edit freely.
// Steps: 1) replace 'unknown' with your concrete return types  2) fill in the function bodies

import {
  ArithParser,
  type ExprNode,
  type TermNode,
  type FactorNode,
  type NumberNode,
  type DigitNode,
  type WspNode,
} from './ArithParser.js'
import { RDParserException } from '@configuredthings/rdp.js'

export function evaluate(input: string): unknown {
  try {
    return evalExpr(ArithParser.parse(input))
  } catch (e) {
    if (e instanceof RDParserException) throw new Error(`parse error: "${input}"`)
    throw e
  }
}

function evalExpr(node: ExprNode): unknown {
  // node.wsp0: WspNode
  // node.term: TermNode
  // node.item2: { wsp0: WspNode; item1: string; wsp1: WspNode; term: TermNode }[]
  // node.wsp1: WspNode
  throw new Error('not implemented')
}

function evalTerm(node: TermNode): unknown {
  // node.factor: FactorNode
  // node.item1: { wsp0: WspNode; item1: string; wsp1: WspNode; factor: FactorNode }[]
  throw new Error('not implemented')
}

function evalFactor(node: FactorNode): unknown {
  // node.item0: { item0: string; expr: ExprNode; item2: string } | NumberNode
  throw new Error('not implemented')
}

function evalNumber(node: NumberNode): unknown {
  // node.digit: DigitNode
  // node.item1: DigitNode[]
  throw new Error('not implemented')
}

function evalDigit(node: DigitNode): unknown {
  // node.item0: string
  throw new Error('not implemented')
}

function evalWsp(node: WspNode): unknown {
  // node.item0: string[]
  throw new Error('not implemented')
}
