// Pipeline scaffold generated by rdp-gen — this file is not regenerated; edit freely.

import { ArithParser, type ExprNode } from './ArithParser.js'
import { RDParserException } from '@configuredthings/rdp.js'

// ── Types ────────────────────────────────────────────────────────────────────

export interface Arith {
  // TODO: define your domain type
}

export interface ValidationError {
  message: string
}

// ── Stage 1: parse ───────────────────────────────────────────────────────────

export function parse(input: string): ExprNode {
  try {
    return ArithParser.parse(input)
  } catch (e) {
    if (e instanceof RDParserException) throw new SyntaxError(e.message)
    throw e
  }
}

// ── Stage 2: validate ────────────────────────────────────────────────────────

export function validate(
  tree: ExprNode,
): { ok: true; tree: ExprNode } | { ok: false; errors: ValidationError[] } {
  const errors: ValidationError[] = []
  // TODO: add validation logic
  return errors.length > 0 ? { ok: false, errors } : { ok: true, tree }
}

// ── Stage 3: transform ───────────────────────────────────────────────────────

export function transform(tree: ExprNode): Arith {
  throw new Error('not implemented')
}
