// Facade scaffold generated by rdp-gen — this file is not regenerated; edit freely.

import { ArithParser, type ExprNode } from './ArithParser.js'
import { RDParserException } from '@configuredthings/rdp.js'

// ── Domain type ──────────────────────────────────────────────────────────────

export interface Arith {
  // TODO: define your domain type
}

export class ArithError extends Error {
  constructor(input: string) {
    super(`invalid input: "${input}"`)
    this.name = 'ArithError'
  }
}

// ── Public API ───────────────────────────────────────────────────────────────

export function parseArith(input: string): Arith {
  let tree: ExprNode
  try {
    tree = ArithParser.parse(input)
  } catch (e) {
    if (e instanceof RDParserException) throw new ArithError(input)
    throw e
  }
  return transform(tree)
}

// ── Private ──────────────────────────────────────────────────────────────────

function transform(tree: ExprNode): Arith {
  throw new Error('not implemented')
}
