/**
 * Format-agnostic TypeScript code emitter.
 *
 * Walks a {@link GrammarAST} and emits a TypeScript source string containing
 * a parser class with one method per production rule. Each rule method returns
 * the parsed node (a typed object) on success or `null` on failure, following
 * the classical recursive descent pattern:
 *
 *   - One private method per grammar rule
 *   - Methods call each other recursively
 *   - `null` signals "this rule didn't match here" (backtrack and try the next alternative)
 *   - `#fail(pos)` restores the saved position and returns `null`
 *
 * The public `parse()` entry point calls the first rule and either returns the
 * root node or throws on failure.
 */

import type { GrammarAST, RuleBody, CoreRuleName } from './ast.js'
import { EBNFParser } from './ebnf-parser.js'
import { ABNFParser } from './abnf-parser.js'
import { detectLeftRecursion } from './left-recursion.js'
import {
  generateTypes,
  generateWalker,
  typeForBody,
  arrayType,
  inferFieldNames,
} from './type-gen.js'

/** Options controlling what `generateParser` emits. */
export type GeneratorOptions = {
  /**
   * Grammar format. Defaults to `'ebnf'`.
   * Use `'abnf'` for RFC 5234 ABNF grammars.
   */
  format?: 'ebnf' | 'abnf'

  /**
   * Class name for the generated parser.
   * @default 'GeneratedParser'
   */
  parserName?: string

  /**
   * Root type name for the generated parse tree types.
   * @default 'ParseTree'
   */
  treeName?: string

  /**
   * When `true`, the generated parser extends `ObservableRDParser` and
   * each production method includes `notifyEnter`/`notifyExit` calls.
   * @default false
   */
  observable?: boolean

  /**
   * When `true`, plain quoted string literals (`"abc"`) in ABNF grammars are matched
   * case-sensitively — the generated parser uses the exact characters as written.
   * When `false` (the RFC 5234 default), unquoted literals are lowercased so the
   * generated parser matches both cases.
   *
   * Has no effect on EBNF grammars or on `%s"..."` / `%i"..."` literals.
   * @default false
   */
  caseSensitiveStrings?: boolean
}

/**
 * Parse a grammar string and emit a TypeScript parser class.
 *
 * @param source - EBNF or ABNF grammar source text.
 * @param options - Generator configuration.
 * @returns A TypeScript source string ready to write to a `.ts` file.
 * @throws {RDParserException} If the grammar is malformed or left-recursive.
 *
 * @example
 * ```ts
 * const ts = generateParser(grammarSource, {
 *   format: 'ebnf',
 *   parserName: 'ArithmeticParser',
 * })
 * ```
 */
export function generateParser(source: string, options: GeneratorOptions = {}): string {
  const format = options.format ?? 'ebnf'
  const parserName = options.parserName ?? 'GeneratedParser'
  const treeName = options.treeName ?? 'ParseTree'
  const observable = options.observable ?? false

  const ast =
    format === 'abnf'
      ? ABNFParser.parse(source, {
          ...(options.caseSensitiveStrings !== undefined && {
            caseSensitiveStrings: options.caseSensitiveStrings,
          }),
        })
      : EBNFParser.parse(source)
  detectLeftRecursion(ast)

  const baseClass = observable ? 'ObservableRDParser' : 'ScannerlessRDParser'
  const importPath = observable ? '@configuredthings/rdp.js/observable' : '@configuredthings/rdp.js'
  const importNames = observable
    ? `{ ObservableRDParser, type ParseObserver }`
    : `{ ScannerlessRDParser }`

  const lines: string[] = []

  lines.push(
    `// This file is generated by rdp-gen (@configuredthings/rdp.js). Do not edit by hand.`,
  )
  lines.push(`// Regenerate with: rdp-gen <grammar-file> --parser-name ${parserName}`)
  lines.push(`//`)
  lines.push(`// Required tsconfig compiler options:`)
  lines.push(`//   target: ES2022  (native # private fields)`)
  lines.push(`//   strict: true`)
  lines.push(`//   noUncheckedIndexedAccess: true`)
  lines.push(`//   moduleResolution: node16 or bundler`)
  lines.push(``)
  lines.push(`import ${importNames} from '${importPath}'`)
  lines.push(``)
  lines.push(`export class ${parserName} extends ${baseClass} {`)
  lines.push(``)
  lines.push(`  private constructor(source: DataView) {`)
  lines.push(`    super(source)`)
  lines.push(`  }`)

  // Emit static entry point + instance parse: calls first rule, enforces full consumption, throws on failure
  const firstRule = ast.rules[0]
  // istanbul ignore else -- grammar parsers always throw on empty input before reaching here
  if (firstRule) {
    const entryMethod = camelCase(firstRule.name)
    const entryType = `${pascalCase(firstRule.name)}Node`

    lines.push(``)
    if (observable) {
      lines.push(`  /** Parse \`input\`, optionally tracing through \`observer\`. */`)
      lines.push(`  static parse(input: string, observer?: ParseObserver): ${entryType} {`)
      lines.push(`    const bytes = new TextEncoder().encode(input)`)
      lines.push(`    const parser = new ${parserName}(new DataView(bytes.buffer))`)
      lines.push(`    if (observer !== undefined) parser.withObserver(observer)`)
      lines.push(`    return parser.parse()`)
      lines.push(`  }`)
    } else {
      lines.push(`  /** Parse \`input\` and return the typed parse tree, or throw on failure. */`)
      lines.push(`  static parse(input: string): ${entryType} {`)
      lines.push(`    const bytes = new TextEncoder().encode(input)`)
      lines.push(`    return new ${parserName}(new DataView(bytes.buffer)).parse()`)
      lines.push(`  }`)
    }

    lines.push(``)
    lines.push(`  parse(): ${entryType} {`)
    lines.push(`    const result = this.#parse_${entryMethod}()`)
    lines.push(`    if (result === null) this.errorAtFurthest()`)
    lines.push(
      `    if (!this.atEnd()) this.error('Unexpected input at position ' + this.getPosition())`,
    )
    lines.push(`    return result`)
    lines.push(`  }`)
  }

  for (const rule of ast.rules) {
    lines.push(``)
    lines.push(...emitMethod(rule.name, rule.body, observable).map((l) => `  ${l}`))
  }

  // Emit backtracking helpers
  lines.push(``)
  lines.push(`  // ── Backtracking helpers ─────────────────────────────────────────────────`)
  lines.push(``)
  lines.push(`  #fail(pos: number): null {`)
  lines.push(`    this.restorePosition(pos)`)
  lines.push(`    return null`)
  lines.push(`  }`)
  if (observable) {
    lines.push(``)
    lines.push(`  #failNotify(pos: number, name: string): null {`)
    lines.push(`    this.notifyExit(name, false)`)
    lines.push(`    this.restorePosition(pos)`)
    lines.push(`    return null`)
    lines.push(`  }`)
  }

  // Emit core rule helpers if any are used
  const usedCoreRules = collectCoreRules(ast)
  if (usedCoreRules.size > 0) {
    lines.push(``)
    lines.push(`  // ── RFC 5234 core rule helpers ───────────────────────────────────────────`)
    for (const name of usedCoreRules) {
      lines.push(``)
      lines.push(...emitCoreRule(name).map((l) => `  ${l}`))
    }
  }

  lines.push(`}`)
  lines.push(``)

  // Append parse tree types
  lines.push(generateTypes(ast, { treeName }))

  // Always append the childNodes walker helper
  lines.push(generateWalker(ast, { treeName }))

  return lines.join('\n')
}

// ── Per-method counters ───────────────────────────────────────────────────────
//
// Each emitMethod call resets this map so variables and labels within a single
// generated method start from index 0. Counts are tracked per hint so that
// `_pos0`, `_pos1` only count position-save variables, `_ch0`, `_ch1` only
// count character captures, and so on.

let methodCounters = new Map<string, number>()

function nextCountFor(key: string): number {
  const n = methodCounters.get(key) ?? 0
  methodCounters.set(key, n + 1)
  return n
}

function namedVar(hint: string): string {
  return `_${hint}${nextCountFor(hint)}`
}

/** Derive a descriptive variable-name hint from a body node. */
function varHint(body: RuleBody): string {
  switch (body.kind) {
    case 'nonTerminal':
      return camelCase(body.name)
    case 'coreRule':
      return body.name.toLowerCase()
    case 'terminal':
      return body.value.length === 1 ? 'ch' : 'lit'
    case 'charValue':
      return 'ch'
    case 'sequence':
      return 'seq'
    case 'alternation':
      return 'alt'
    case 'optional':
      return varHint(body.item)
    case 'zeroOrMore':
    case 'oneOrMore':
    case 'repetition':
      return varHint(body.item) + 's'
    case 'exception':
      return varHint(body.item)
  }
}

// ── Method emitter ────────────────────────────────────────────────────────────

function emitMethod(name: string, body: RuleBody, observable: boolean): string[] {
  methodCounters = new Map()
  const methodName = camelCase(name)
  const nodeName = `${pascalCase(name)}Node`
  const lines: string[] = []

  lines.push(`#parse_${methodName}(): ${nodeName} | null {`)
  if (observable) {
    lines.push(`  this.notifyEnter('${name}')`)
  }

  const topFail = observable
    ? `return this.#failNotify(start, '${name}')`
    : `return this.#fail(start)`

  // Flatten top-level sequences so each item is a separate captured field.
  // Non-sequence bodies become a single item.
  const bodyItems = body.kind === 'sequence' ? body.items : [body]
  const fieldNames = inferFieldNames(bodyItems)
  const itemVars: string[] = []

  // Generate body lines first so we can detect whether `start` is actually
  // referenced (it won't be for rules whose body can never fail, e.g. zeroOrMore).
  const bodyLines: string[] = []
  for (const item of bodyItems) {
    const { lines: captureLines, varName } = emitCapture(item, observable, topFail)
    bodyLines.push(...captureLines.map((l) => `  ${l}`))
    itemVars.push(varName)
  }

  const startUsed = bodyLines.some((l) => l.includes('start'))
  if (!startUsed) {
    lines.push(`  // eslint-disable-next-line @typescript-eslint/no-unused-vars`)
  }
  lines.push(`  const start = this.getPosition()`)
  lines.push(...bodyLines)

  if (observable) {
    lines.push(`  this.notifyExit('${name}', true)`)
  }

  const fields = itemVars.map((v, i) => `${fieldNames[i]}: ${v}`).join(', ')
  lines.push(`  return { kind: '${name}', ${fields} }`)
  lines.push(`}`)
  return lines
}

// ── Capture emitter ───────────────────────────────────────────────────────────

/**
 * Emit code that captures the result of matching `body` into a fresh variable.
 *
 * @param body       - The grammar body to match.
 * @param obs        - Whether the parser is observable.
 * @param failStmt   - The statement (complete, with semicolon if needed) to execute
 *                     on failure. At rule level this is `return this.#fail(start)`.
 *                     Inside loops/optionals it is a labeled break with position restore.
 * @returns `lines` to emit and `varName` holding the captured result.
 *          For mandatory items, `varName` is non-null after `lines` execute (or `failStmt` fired).
 *          For optional/zero-or-more items, `varName` may be `null` or `[]`.
 */
function emitCapture(
  body: RuleBody,
  observable: boolean,
  failStmt: string,
): { lines: string[]; varName: string } {
  switch (body.kind) {
    // ── Atoms ──────────────────────────────────────────────────────────────

    case 'terminal': {
      const lines: string[] = []
      const chars = body.value.split('')
      if (chars.length === 1) {
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        const ch = chars[0]!
        const code = ch.charCodeAt(0)
        const v = namedVar('ch')
        lines.push(
          `const ${v} = this.readChar(0x${code.toString(16).padStart(2, '0')}) // ${JSON.stringify(ch)}`,
        )
        lines.push(`if (${v} === null) ${failStmt}`)
        return { lines, varName: v }
      } else {
        // Multi-char terminal: match each char with matchChar (no position change on failure),
        // then capture the whole literal as a string.
        for (const ch of chars) {
          const code = ch.charCodeAt(0)
          lines.push(
            `if (!this.matchChar(0x${code.toString(16).padStart(2, '0')})) ${failStmt} // ${JSON.stringify(ch)}`,
          )
        }
        const v = namedVar('lit')
        lines.push(`const ${v} = ${JSON.stringify(body.value)}`)
        return { lines, varName: v }
      }
    }

    case 'nonTerminal': {
      const v = namedVar(camelCase(body.name))
      return {
        lines: [
          `const ${v} = this.#parse_${camelCase(body.name)}()`,
          `if (${v} === null) ${failStmt}`,
        ],
        varName: v,
      }
    }

    case 'coreRule': {
      const v = namedVar(body.name.toLowerCase())
      return {
        lines: [
          `const ${v} = this.#${body.name.toLowerCase()}()`,
          `if (${v} === null) ${failStmt}`,
        ],
        varName: v,
      }
    }

    case 'charValue': {
      const v = namedVar('ch')
      const lines: string[] = []
      if (body.range !== undefined) {
        const [lo, hi] = body.range
        lines.push(`const ${v} = this.readCharRange(0x${lo.toString(16)}, 0x${hi.toString(16)})`)
        lines.push(`if (${v} === null) ${failStmt}`)
      } else if (body.codepoints.length === 1) {
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        const cp = body.codepoints[0]!
        lines.push(`const ${v} = this.readChar(0x${cp.toString(16).padStart(2, '0')})`)
        lines.push(`if (${v} === null) ${failStmt}`)
      } else {
        // Multiple specific codepoints: try each with readChar (no advance on failure)
        const foundL = `found_ch${nextCountFor('found_ch')}`
        lines.push(`let ${v}!: string`)
        lines.push(`${foundL}: {`)
        for (const cp of body.codepoints) {
          const altL = `alt_ch${nextCountFor('alt_ch')}`
          lines.push(`  ${altL}: {`)
          lines.push(`    const ch = this.readChar(0x${cp.toString(16).padStart(2, '0')})`)
          lines.push(`    if (ch === null) break ${altL}`)
          lines.push(`    ${v} = ch`)
          lines.push(`    break ${foundL}`)
          lines.push(`  }`)
        }
        lines.push(`  ${failStmt}`)
        lines.push(`}`)
      }
      return { lines, varName: v }
    }

    // ── Composites ─────────────────────────────────────────────────────────

    case 'sequence': {
      // Sequence as a sub-expression (inside a loop or alternation):
      // emit each item with the same failStmt, then assemble into an anonymous object.
      const allLines: string[] = []
      const itemVars: string[] = []
      for (const item of body.items) {
        const { lines: il, varName } = emitCapture(item, observable, failStmt)
        allLines.push(...il)
        itemVars.push(varName)
      }
      const v = namedVar('seq')
      const fieldNames = inferFieldNames(body.items)
      const fields = itemVars.map((name, i) => `${fieldNames[i]}: ${name}`).join(', ')
      allLines.push(`const ${v} = { ${fields} }`)
      return { lines: allLines, varName: v }
    }

    case 'alternation': {
      const type = typeForBody(body)
      const hint = varHint(body)
      const v = namedVar('alt')
      const foundLabel = `found_${hint}${nextCountFor('found_' + hint)}`
      const lines: string[] = [``, `let ${v}!: ${type}`, `${foundLabel}: {`]
      for (const item of body.items) {
        const altLabel = `alt_${varHint(item)}${nextCountFor('alt_' + varHint(item))}`
        const savedPos = namedVar('pos')
        const innerFail = `{ if (this.getPosition() !== ${savedPos}) throw new Error('LL(1) violation: alternative consumed input up to position ' + this.getPosition() + ' before failing (started at ' + ${savedPos} + ') — two alternatives share a common prefix'); this.restorePosition(${savedPos}); break ${altLabel} }`
        const inner = emitCapture(item, observable, innerFail)
        lines.push(`  ${altLabel}: {`)
        lines.push(`    const ${savedPos} = this.getPosition()`)
        for (const l of inner.lines) lines.push(`    ${l}`)
        lines.push(`    ${v} = ${inner.varName}`)
        lines.push(`    break ${foundLabel}`)
        lines.push(`  }`)
      }
      lines.push(`  ${failStmt}`)
      lines.push(`}`)
      return { lines, varName: v }
    }

    case 'optional': {
      const type = typeForBody(body.item)
      const v = namedVar(varHint(body.item))
      const optLabel = `opt_${varHint(body.item)}${nextCountFor('opt_' + varHint(body.item))}`
      const savedPos = namedVar('pos')
      const innerFail = `{ this.restorePosition(${savedPos}); break ${optLabel} }`
      const inner = emitCapture(body.item, observable, innerFail)
      const lines: string[] = [
        `let ${v}: ${type} | null = null`,
        `${optLabel}: {`,
        `  const ${savedPos} = this.getPosition()`,
        ...inner.lines.map((l) => `  ${l}`),
        `  ${v} = ${inner.varName}`,
        `}`,
      ]
      return { lines, varName: v }
    }

    case 'zeroOrMore': {
      const arr = namedVar(varHint(body.item) + 's')
      const loopLabel = `loop_${varHint(body.item)}${nextCountFor('loop_' + varHint(body.item))}`
      const savedPos = namedVar('pos')
      const innerFail = `{ this.restorePosition(${savedPos}); break ${loopLabel} }`
      const inner = emitCapture(body.item, observable, innerFail)
      const lines: string[] = [
        `const ${arr}: ${arrayType(body.item)} = []`,
        `${loopLabel}: while (true) {`,
        `  const ${savedPos} = this.getPosition()`,
        ...inner.lines.map((l) => `  ${l}`),
        `  ${arr}.push(${inner.varName})`,
        `}`,
      ]
      return { lines, varName: arr }
    }

    case 'oneOrMore': {
      const arr = namedVar(varHint(body.item) + 's')
      // First occurrence is mandatory (uses outer failStmt)
      const first = emitCapture(body.item, observable, failStmt)
      // Subsequent occurrences via loop
      const loopLabel = `loop_${varHint(body.item)}${nextCountFor('loop_' + varHint(body.item))}`
      const savedPos = namedVar('pos')
      const innerFail = `{ this.restorePosition(${savedPos}); break ${loopLabel} }`
      const rest = emitCapture(body.item, observable, innerFail)
      const lines: string[] = [
        ...first.lines,
        `const ${arr}: ${arrayType(body.item)} = [${first.varName}]`,
        `${loopLabel}: while (true) {`,
        `  const ${savedPos} = this.getPosition()`,
        ...rest.lines.map((l) => `  ${l}`),
        `  ${arr}.push(${rest.varName})`,
        `}`,
      ]
      return { lines, varName: arr }
    }

    case 'exception': {
      // A - B: try B at current position; if B matches, fail. Else try A.
      const savedPos = namedVar('pos')
      const excLabel = `exc_${varHint(body.except)}${nextCountFor('exc_' + varHint(body.except))}`
      const excMatched = namedVar('excMatched')
      const lines: string[] = []
      lines.push(`const ${savedPos} = this.getPosition()`)
      lines.push(`let ${excMatched} = false`)
      lines.push(`${excLabel}: {`)
      const excCapture = emitCapture(body.except, observable, `break ${excLabel}`)
      for (const l of excCapture.lines) lines.push(`  ${l}`)
      lines.push(`  ${excMatched} = true`)
      lines.push(`}`)
      lines.push(`this.restorePosition(${savedPos})`)
      lines.push(`if (${excMatched}) ${failStmt}`)
      const mainCapture = emitCapture(body.item, observable, failStmt)
      lines.push(...mainCapture.lines)
      return { lines, varName: mainCapture.varName }
    }

    case 'repetition': {
      const arr = namedVar(varHint(body.item) + 's')
      const repLabel = `rep_${varHint(body.item)}${nextCountFor('rep_' + varHint(body.item))}`
      const savedPos = namedVar('pos')
      const innerFail = `{ this.restorePosition(${savedPos}); break ${repLabel} }`
      const inner = emitCapture(body.item, observable, innerFail)
      const maxCond = body.max !== null ? `count < ${body.max}` : 'true'
      const lines: string[] = [
        `const ${arr}: ${arrayType(body.item)} = []`,
        `{`,
        `  let count = 0`,
        `  ${repLabel}: while (${maxCond}) {`,
        `    const ${savedPos} = this.getPosition()`,
        ...inner.lines.map((l) => `    ${l}`),
        `    ${arr}.push(${inner.varName})`,
        `    count++`,
        `  }`,
        `  if (count < ${body.min}) ${failStmt}`,
        `}`,
      ]
      return { lines, varName: arr }
    }
  }
}

// ── Core rule collection ──────────────────────────────────────────────────────

function collectCoreRules(ast: GrammarAST): Set<CoreRuleName> {
  const found = new Set<CoreRuleName>()
  for (const rule of ast.rules) collectCoreRulesInBody(rule.body, found)
  return found
}

function collectCoreRulesInBody(body: RuleBody, out: Set<CoreRuleName>): void {
  switch (body.kind) {
    case 'coreRule':
      out.add(body.name)
      break
    case 'sequence':
    case 'alternation':
      for (const item of body.items) collectCoreRulesInBody(item, out)
      break
    case 'optional':
    case 'zeroOrMore':
    case 'oneOrMore':
    case 'repetition':
      collectCoreRulesInBody(body.item, out)
      break
    default:
      break
  }
}

// ── Core rule helpers ─────────────────────────────────────────────────────────

function emitCoreRule(name: CoreRuleName): string[] {
  const body = CORE_RULE_BODIES[name]
  return [`#${name.toLowerCase()}(): string | null {`, `  ${body}`, `}`]
}

const CORE_RULE_BODIES: Record<CoreRuleName, string> = {
  ALPHA: `const cp = this.peek(); if (cp === null || !((cp >= 0x41 && cp <= 0x5a) || (cp >= 0x61 && cp <= 0x7a))) return null; this.advance(); return String.fromCharCode(cp)`,
  BIT: `const cp = this.peek(); if (cp !== 0x30 && cp !== 0x31) return null; this.advance(); return String.fromCharCode(cp)`,
  CHAR: `const cp = this.peek(); if (cp === null || cp < 0x01 || cp > 0x7f) return null; this.advance(); return String.fromCharCode(cp)`,
  CR: `return this.matchChar(0x0d) ? '\\r' : null`,
  CRLF: `{ const pos = this.getPosition(); if (!this.matchChar(0x0d) || !this.matchChar(0x0a)) { this.restorePosition(pos); return null } return '\\r\\n' }`,
  CTL: `const cp = this.peek(); if (cp === null || !(cp < 0x20 || cp === 0x7f)) return null; this.advance(); return String.fromCharCode(cp)`,
  DIGIT: `const cp = this.peek(); if (cp === null || cp < 0x30 || cp > 0x39) return null; this.advance(); return String.fromCharCode(cp)`,
  DQUOTE: `return this.matchChar(0x22) ? '"' : null`,
  HEXDIG: `const cp = this.peek(); if (cp === null || !((cp >= 0x30 && cp <= 0x39)||(cp >= 0x41 && cp <= 0x46)||(cp >= 0x61 && cp <= 0x66))) return null; this.advance(); return String.fromCharCode(cp)`,
  HTAB: `return this.matchChar(0x09) ? '\\t' : null`,
  LF: `return this.matchChar(0x0a) ? '\\n' : null`,
  LWSP: `while (this.matchChar(0x20) || this.matchChar(0x09) || (this.matchChar(0x0d) && this.matchChar(0x0a))) {} return ''`,
  OCTET: `const cp = this.peek(); if (cp === null) return null; this.advance(); return String.fromCharCode(cp)`,
  SP: `return this.matchChar(0x20) ? ' ' : null`,
  VCHAR: `const cp = this.peek(); if (cp === null || cp < 0x21 || cp > 0x7e) return null; this.advance(); return String.fromCharCode(cp)`,
  WSP: `const cp = this.peek(); if (cp !== 0x20 && cp !== 0x09) return null; this.advance(); return String.fromCharCode(cp)`,
}

// ── Utilities ─────────────────────────────────────────────────────────────────

function camelCase(name: string): string {
  const s = name.replace(/[-_]([a-zA-Z])/g, (_, c: string) => c.toUpperCase())
  return s.charAt(0).toLowerCase() + s.slice(1)
}

function pascalCase(name: string): string {
  return name.replace(/(^|[-_])([a-zA-Z])/g, (_, __, c: string) => c.toUpperCase())
}
