/**
 * Scaffold generators — emit one-time starter files for each usage pattern.
 *
 * Unlike the generated parser, scaffold output is intended to be edited by hand
 * and is NOT regenerated. It is a starting point, not a derived artefact.
 */

import type { GrammarAST, ProductionRule } from './ast.js'
import { EBNFParser } from './ebnf-parser.js'
import { ABNFParser } from './abnf-parser.js'
import { detectLeftRecursion } from './left-recursion.js'
import type { GeneratorOptions } from './codegen.js'
import { inferFieldNames, typeForBody } from './type-gen.js'

/** The usage pattern to scaffold. */
export type ScaffoldPattern = 'evaluator' | 'facade' | 'pipeline' | 'walker'

/**
 * Generate a one-time scaffold file for the given usage pattern.
 *
 * The scaffold is intended as a starting point — edit it freely. Unlike the
 * generated parser it is not designed to be regenerated from the grammar.
 *
 * @param source - EBNF or ABNF grammar source text.
 * @param pattern - The usage pattern to scaffold.
 * @param options - Generator configuration (same options as `generateParser`).
 * @returns A TypeScript source string ready to write to a `.ts` file.
 * @throws {RDParserException} If the grammar is malformed or left-recursive.
 */
export function generateScaffold(
  source: string,
  pattern: ScaffoldPattern,
  options: GeneratorOptions = {},
): string {
  const format = options.format ?? 'ebnf'
  const parserName = options.parserName ?? 'GeneratedParser'
  const treeName = options.treeName ?? 'ParseTree'

  const ast =
    format === 'abnf'
      ? ABNFParser.parse(source, {
          ...(options.caseSensitiveStrings !== undefined && {
            caseSensitiveStrings: options.caseSensitiveStrings,
          }),
        })
      : EBNFParser.parse(source)
  detectLeftRecursion(ast)

  switch (pattern) {
    case 'evaluator':
      return generateEvaluatorScaffold(ast, parserName)
    case 'facade':
      return generateFacadeScaffold(ast, parserName)
    case 'pipeline':
      return generatePipelineScaffold(ast, parserName)
    case 'walker':
      return generateWalkerScaffold(ast, parserName, treeName)
  }
}

// ── Evaluator scaffold ────────────────────────────────────────────────────────

function generateEvaluatorScaffold(ast: GrammarAST, parserName: string): string {
  const firstRule = ast.rules[0]
  if (!firstRule) return ''

  const modulePath = `./${parserName}.js`
  const nodeTypes = ast.rules.map((r) => `${pascalCase(r.name)}Node`)
  const lines: string[] = []

  lines.push(
    `// Evaluator scaffold generated by rdp-gen — this file is not regenerated; edit freely.`,
  )
  lines.push(
    `// Steps: 1) replace 'unknown' with your concrete return types  2) fill in the function bodies`,
  )
  lines.push(
    `//        3) remove eslint-disable-next-line comments — present only to keep stubs lint-clean`,
  )
  lines.push(``)
  lines.push(`import {`)
  lines.push(`  ${parserName},`)
  for (const t of nodeTypes) lines.push(`  type ${t},`)
  lines.push(`} from '${modulePath}'`)
  lines.push(`import { RDParserException } from '@configuredthings/rdp.js'`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Parse \`input\` and evaluate it to a result.`)
  lines.push(` *`)
  lines.push(` * Replace the \`unknown\` return type with your concrete result type once`)
  lines.push(` * you have filled in the \`eval*\` functions below.`)
  lines.push(` *`)
  lines.push(` * @param input - Source string to parse and evaluate.`)
  lines.push(` * @returns The evaluated result (narrowed once implemented).`)
  lines.push(` * @throws {Error} If \`input\` does not match the grammar.`)
  lines.push(` */`)
  lines.push(`export function evaluate(input: string): unknown {`)
  lines.push(`  try {`)
  lines.push(`    return eval${pascalCase(firstRule.name)}(${parserName}.parse(input))`)
  lines.push(`  } catch (e) {`)
  lines.push(
    `    if (e instanceof RDParserException) throw new Error(\`parse error: "\${input}"\`)`,
  )
  lines.push(`    throw e`)
  lines.push(`  }`)
  lines.push(`}`)

  for (const rule of ast.rules) {
    const nodeType = `${pascalCase(rule.name)}Node`
    lines.push(``)
    lines.push(`/**`)
    lines.push(` * Evaluate a \`${rule.name}\` node.`)
    lines.push(` *`)
    lines.push(` * @param node - The {@link ${nodeType}} to evaluate.`)
    lines.push(` * @returns The evaluated result (replace \`unknown\` with your concrete type).`)
    lines.push(` */`)
    lines.push(`// eslint-disable-next-line @typescript-eslint/no-unused-vars`)
    lines.push(`function eval${pascalCase(rule.name)}(node: ${nodeType}): unknown {`)
    for (const hint of fieldHints(rule)) lines.push(`  // ${hint}`)
    lines.push(`  throw new Error('not implemented')`)
    lines.push(`}`)
  }

  lines.push(``)
  return lines.join('\n')
}

// ── Facade scaffold ───────────────────────────────────────────────────────────

function generateFacadeScaffold(ast: GrammarAST, parserName: string): string {
  const firstRule = ast.rules[0]
  if (!firstRule) return ''

  const base = stripParserSuffix(parserName)
  const modulePath = `./${parserName}.js`
  const firstNodeType = `${pascalCase(firstRule.name)}Node`
  const domainType = base
  const errorClass = `${base}Error`
  const entryFn = `parse${base}`
  const lines: string[] = []

  lines.push(`// Facade scaffold generated by rdp-gen — this file is not regenerated; edit freely.`)
  lines.push(
    `// Steps: 1) define ${domainType} fields  2) fill in transform()  3) remove eslint-disable-next-line comments`,
  )
  lines.push(``)
  lines.push(`import { ${parserName}, type ${firstNodeType} } from '${modulePath}'`)
  lines.push(`import { RDParserException } from '@configuredthings/rdp.js'`)
  lines.push(``)
  lines.push(`// ── Domain type ──────────────────────────────────────────────────────────────`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Domain representation of a successfully parsed input.`)
  lines.push(` *`)
  lines.push(` * Replace this empty interface with the fields that make sense for your domain.`)
  lines.push(` * {@link ${entryFn}} returns this type once {@link transform} is implemented.`)
  lines.push(` */`)
  lines.push(`// eslint-disable-next-line @typescript-eslint/no-empty-object-type`)
  lines.push(`export interface ${domainType} {`)
  lines.push(`  // TODO: define your domain type`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Thrown by {@link ${entryFn}} when \`input\` does not match the grammar.`)
  lines.push(` */`)
  lines.push(`export class ${errorClass} extends Error {`)
  lines.push(`  constructor(input: string) {`)
  lines.push(`    super(\`invalid input: "\${input}"\`)`)
  lines.push(`    this.name = '${errorClass}'`)
  lines.push(`  }`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`// ── Public API ───────────────────────────────────────────────────────────────`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Parse \`input\` and return a domain {@link ${domainType}} object.`)
  lines.push(` *`)
  lines.push(` * @param input - Source string to parse.`)
  lines.push(` * @returns A {@link ${domainType}} representing the parsed input.`)
  lines.push(` * @throws {@link ${errorClass}} If \`input\` does not match the grammar.`)
  lines.push(` */`)
  lines.push(`export function ${entryFn}(input: string): ${domainType} {`)
  lines.push(`  let tree: ${firstNodeType}`)
  lines.push(`  try {`)
  lines.push(`    tree = ${parserName}.parse(input)`)
  lines.push(`  } catch (e) {`)
  lines.push(`    if (e instanceof RDParserException) throw new ${errorClass}(input)`)
  lines.push(`    throw e`)
  lines.push(`  }`)
  lines.push(`  return transform(tree)`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`// ── Private ──────────────────────────────────────────────────────────────────`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Convert the raw parse tree into a {@link ${domainType}} domain object.`)
  lines.push(` *`)
  lines.push(` * @param tree - The root {@link ${firstNodeType}} returned by the parser.`)
  lines.push(` * @returns The domain object.`)
  lines.push(` */`)
  lines.push(`// eslint-disable-next-line @typescript-eslint/no-unused-vars`)
  lines.push(`function transform(tree: ${firstNodeType}): ${domainType} {`)
  lines.push(`  throw new Error('not implemented')`)
  lines.push(`}`)
  lines.push(``)

  return lines.join('\n')
}

// ── Pipeline scaffold ─────────────────────────────────────────────────────────

function generatePipelineScaffold(ast: GrammarAST, parserName: string): string {
  const firstRule = ast.rules[0]
  if (!firstRule) return ''

  const base = stripParserSuffix(parserName)
  const modulePath = `./${parserName}.js`
  const firstNodeType = `${pascalCase(firstRule.name)}Node`
  const domainType = base
  const lines: string[] = []

  lines.push(
    `// Pipeline scaffold generated by rdp-gen — this file is not regenerated; edit freely.`,
  )
  lines.push(
    `// Steps: 1) define ${domainType} fields  2) fill in transform()  3) remove eslint-disable-next-line comments`,
  )
  lines.push(``)
  lines.push(`import { ${parserName}, type ${firstNodeType} } from '${modulePath}'`)
  lines.push(`import { RDParserException } from '@configuredthings/rdp.js'`)
  lines.push(``)
  lines.push(`// ── Types ────────────────────────────────────────────────────────────────────`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Domain representation produced by the final pipeline stage.`)
  lines.push(` *`)
  lines.push(
    ` * Replace this empty interface with the fields you want {@link transform} to return.`,
  )
  lines.push(` */`)
  lines.push(`// eslint-disable-next-line @typescript-eslint/no-empty-object-type`)
  lines.push(`export interface ${domainType} {`)
  lines.push(`  // TODO: define your domain type`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * A single semantic error found during {@link validate}.`)
  lines.push(` */`)
  lines.push(`export interface ValidationError {`)
  lines.push(`  message: string`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`// ── Stage 1: parse ───────────────────────────────────────────────────────────`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Stage 1 — parse \`input\` into a typed parse tree.`)
  lines.push(` *`)
  lines.push(` * @param input - Source string to parse.`)
  lines.push(` * @returns The root {@link ${firstNodeType}} of the parse tree.`)
  lines.push(` * @throws {SyntaxError} If \`input\` does not match the grammar.`)
  lines.push(` */`)
  lines.push(`export function parse(input: string): ${firstNodeType} {`)
  lines.push(`  try {`)
  lines.push(`    return ${parserName}.parse(input)`)
  lines.push(`  } catch (e) {`)
  lines.push(`    if (e instanceof RDParserException) throw new SyntaxError(e.message)`)
  lines.push(`    throw e`)
  lines.push(`  }`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`// ── Stage 2: validate ────────────────────────────────────────────────────────`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Stage 2 — check the parse tree for semantic errors.`)
  lines.push(` *`)
  lines.push(` * @param tree - Parse tree returned by {@link parse}.`)
  lines.push(
    ` * @returns \`{ ok: true, tree }\` when valid, or \`{ ok: false, errors }\` otherwise.`,
  )
  lines.push(` */`)
  lines.push(`export function validate(`)
  lines.push(`  tree: ${firstNodeType},`)
  lines.push(`): { ok: true; tree: ${firstNodeType} } | { ok: false; errors: ValidationError[] } {`)
  lines.push(`  const errors: ValidationError[] = []`)
  lines.push(`  // TODO: add validation logic`)
  lines.push(`  return errors.length > 0 ? { ok: false, errors } : { ok: true, tree }`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`// ── Stage 3: transform ───────────────────────────────────────────────────────`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(
    ` * Stage 3 — convert the validated parse tree into a domain {@link ${domainType}} object.`,
  )
  lines.push(` *`)
  lines.push(` * @param tree - Validated parse tree from {@link validate}.`)
  lines.push(` * @returns The domain object.`)
  lines.push(` */`)
  lines.push(`// eslint-disable-next-line @typescript-eslint/no-unused-vars`)
  lines.push(`export function transform(tree: ${firstNodeType}): ${domainType} {`)
  lines.push(`  throw new Error('not implemented')`)
  lines.push(`}`)
  lines.push(``)

  return lines.join('\n')
}

// ── Walker scaffold ───────────────────────────────────────────────────────────

function generateWalkerScaffold(ast: GrammarAST, parserName: string, treeName: string): string {
  const firstRule = ast.rules[0]
  if (!firstRule) return ''

  const modulePath = `./${parserName}.js`
  const lines: string[] = []

  lines.push(`// Walker scaffold generated by rdp-gen — this file is not regenerated; edit freely.`)
  lines.push(`// --walker adds childNodes() to the parser file; this scaffold shows how to use it.`)
  lines.push(
    `// Once you uncomment the visitor below, remove the eslint-disable-next-line comments.`,
  )
  lines.push(``)
  lines.push(`// eslint-disable-next-line @typescript-eslint/no-unused-vars`)
  lines.push(`import { ${parserName}, childNodes, type ${treeName} } from '${modulePath}'`)
  lines.push(`// eslint-disable-next-line @typescript-eslint/no-unused-vars`)
  lines.push(`import { visit, type Visitor } from '@configuredthings/rdp.js'`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Walk \`root\` depth-first (pre-order), calling \`fn\` on every node.`)
  lines.push(` *`)
  lines.push(` * @param root - The tree node to start from.`)
  lines.push(` * @param fn - Called once per node visited, before its children.`)
  lines.push(` */`)
  lines.push(`export function walk(root: ${treeName}, fn: (node: ${treeName}) => void): void {`)
  lines.push(`  fn(root)`)
  lines.push(`  for (const child of childNodes(root)) walk(child, fn)`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`// Add handlers for the node kinds you care about.`)
  lines.push(`// Use Required<Visitor<${treeName}>> to enforce that every kind is handled.`)
  lines.push(`//`)
  lines.push(`// const visitor: Visitor<${treeName}> = {`)
  for (const rule of ast.rules) {
    lines.push(`//   '${rule.name}': (node) => { /* ... */ },`)
  }
  lines.push(`// }`)
  lines.push(`//`)
  lines.push(`// walk(${parserName}.parse(input), (node) => visit(node, visitor))`)
  lines.push(``)

  return lines.join('\n')
}

// ── Init scaffold ─────────────────────────────────────────────────────────────

/** Options for the `init` project scaffold. */
export type InitScaffoldOptions = {
  /** Class name for the hand-written parser (e.g. `MyParser`). */
  className: string
  /** When true, extends `ObservableRDParser` with `notifyEnter`/`notifyExit` stubs. */
  observable?: boolean
}

/**
 * Generate the starter parser file content for `rdp-gen init`.
 *
 * @param options - Class name and observable flag.
 * @returns A TypeScript source string for the initial parser file.
 */
export function generateInitScaffold(options: InitScaffoldOptions): string {
  const { className, observable } = options

  if (observable) {
    return `\
import { ObservableRDParser, ParseObserver } from '@configuredthings/rdp.js/observable'

export class ${className} extends ObservableRDParser {
  private constructor(source: DataView) {
    super(source)
  }

  static parse(input: string, observer?: ParseObserver): unknown {
    const bytes = new TextEncoder().encode(input)
    const parser = new ${className}(new DataView(bytes.buffer))
    if (observer !== undefined) parser.withObserver(observer)
    return parser.#parseRoot()
  }

  #parseRoot(): unknown {
    this.notifyEnter('root')
    // TODO: implement your top-level production rule.
    // Add private methods for each grammar rule, e.g. #parseExpression(), #parseTerm().
    // Use this.peek(), this.matchChar(), this.expectChar(), this.readChar(), this.atEnd(), etc.
    // Call this.error() to signal a parse failure at the current position.
    // Call this.notifyEnter(name) at the top and this.notifyExit(name, matched) before each return.
    if (!this.atEnd()) this.error('unexpected input')
    this.notifyExit('root', false)
    throw new Error('not implemented')
  }
}
`
  }

  return `\
import { RDParser } from '@configuredthings/rdp.js'

export class ${className} extends RDParser {
  private constructor(source: DataView) {
    super(source)
  }

  static parse(input: string): unknown {
    const bytes = new TextEncoder().encode(input)
    return new ${className}(new DataView(bytes.buffer)).#parseRoot()
  }

  #parseRoot(): unknown {
    // TODO: implement your top-level production rule.
    // Add private methods for each grammar rule, e.g. #parseExpression(), #parseTerm().
    // Use this.peek(), this.matchChar(), this.expectChar(), this.readChar(), this.atEnd(), etc.
    // Call this.error() to signal a parse failure at the current position.
    if (!this.atEnd()) this.error('unexpected input')
    throw new Error('not implemented')
  }
}
`
}

// ── Utilities ─────────────────────────────────────────────────────────────────

/** Strip a trailing `Parser` suffix to derive a base name for domain types. */
function stripParserSuffix(parserName: string): string {
  return parserName.endsWith('Parser') ? parserName.slice(0, -6) : parserName
}

function pascalCase(name: string): string {
  return name.replace(/(^|[-_])([a-zA-Z])/g, (_, __, c: string) => c.toUpperCase())
}
/**
 * Generate `node.field: Type` hint strings for a production rule's fields,
 * mirroring the shape of the emitted `XxxNode` type. Used as inline comments
 * in evaluator stub functions so users can see the available fields without
 * cross-referencing the generated types file.
 */
function fieldHints(rule: ProductionRule): string[] {
  const bodyItems = rule.body.kind === 'sequence' ? rule.body.items : [rule.body]
  const names = inferFieldNames(bodyItems)
  return bodyItems.map((item, i) => `node.${names[i]}: ${typeForBody(item)}`)
}
