/**
 * Parse tree type emitter — generates TypeScript discriminated union types
 * from a {@link GrammarAST}.
 *
 * Produces one type alias per production rule plus a root `ParseTree` union.
 */

import type { GrammarAST, ProductionRule, RuleBody } from './ast.js'

/**
 * Infer field names for a list of grammar body items.
 *
 * Non-terminal references take the camelCase of the referenced rule name.
 * All other items (terminals, core rules, composites) fall back to `item`n.
 * When the same non-terminal name appears more than once, all occurrences are
 * suffixed with a zero-based index (`year0`, `year1`, …).
 */
export function inferFieldNames(items: RuleBody[]): string[] {
  // First pass: candidate name (null = use item-n fallback)
  const candidates = items.map((item): string | null =>
    item.kind === 'nonTerminal' ? camelCase(item.name) : null,
  )

  // Count occurrences of each non-null candidate
  const counts = new Map<string, number>()
  for (const c of candidates) {
    if (c !== null) counts.set(c, (counts.get(c) ?? 0) + 1)
  }

  // Second pass: resolve duplicates with a numeric suffix
  const seen = new Map<string, number>()
  return candidates.map((candidate, i) => {
    if (candidate === null) return `item${i}`
    if ((counts.get(candidate) ?? 0) > 1) {
      const occ = seen.get(candidate) ?? 0
      seen.set(candidate, occ + 1)
      return `${candidate}${occ}`
    }
    return candidate
  })
}

/** Options for the type generator. */
export type TypeGenOptions = {
  /** Root type name for the generated union. Defaults to `'ParseTree'`. */
  treeName?: string
}

/**
 * Emit TypeScript discriminated union types for the given grammar.
 *
 * @param ast - The grammar to generate types for.
 * @param options - Optional configuration.
 * @returns A TypeScript source string containing the type definitions.
 */
export function generateTypes(ast: GrammarAST, options: TypeGenOptions = {}): string {
  const treeName = options.treeName ?? 'ParseTree'
  const lines: string[] = []

  lines.push(
    '// This file is generated by rdp-gen (@configuredthings/rdp.js). Do not edit by hand.',
  )
  lines.push('')
  lines.push(...emitTypeDeclarations(ast, treeName))

  return lines.join('\n')
}

/**
 * Emit just the type declaration lines (node types + tree union) without a file header.
 * Used when embedding types inside another scaffold file.
 */
export function emitTypeDeclarations(ast: GrammarAST, treeName: string): string[] {
  const lines: string[] = []

  for (const rule of ast.rules) {
    lines.push(...emitRuleType(rule))
    lines.push('')
  }

  const nodeNames = ast.rules.map((r) => pascalCase(r.name) + 'Node')
  lines.push(`export type ${treeName} =`)
  for (let i = 0; i < nodeNames.length; i++) {
    lines.push(`  | ${nodeNames[i]}`)
  }
  lines.push('')

  return lines
}

/**
 * Returns the TypeScript type string for a grammar body node.
 *
 * Used both by the type emitter and by `codegen.ts` when declaring capture variables.
 *
 * - Terminals, core rules, and char values → `string`
 * - Non-terminals → `XxxNode`
 * - Sequences → anonymous object type `{ item0: T0; item1: T1; ... }`
 * - Alternations → union of the alternative types
 * - Optional → `T | null`
 * - Zero-or-more, one-or-more, repetition → `T[]`
 */
export function typeForBody(body: RuleBody): string {
  switch (body.kind) {
    case 'terminal':
    case 'coreRule':
    case 'charValue':
      return 'string'
    case 'nonTerminal':
      return `${pascalCase(body.name)}Node`
    case 'sequence': {
      const names = inferFieldNames(body.items)
      return `{ ${body.items.map((item, i) => `${names[i]}: ${typeForBody(item)}`).join('; ')} }`
    }
    case 'alternation': {
      const types = [...new Set(body.items.map(typeForBody))]
      return types.join(' | ')
    }
    case 'optional':
      return `${typeForBody(body.item)} | null`
    case 'zeroOrMore':
    case 'oneOrMore':
    case 'repetition':
      return arrayType(body.item)
    case 'exception':
      return typeForBody(body.item)
  }
}

/**
 * Returns the TypeScript array type for a repeated grammar body.
 * Wraps union item types in parentheses so `A | B | C` becomes `(A | B | C)[]`
 * rather than the incorrectly-parsed `A | B | C[]`.
 */
export function arrayType(item: RuleBody): string {
  const inner = typeForBody(item)
  return inner.includes(' | ') ? `(${inner})[]` : `${inner}[]`
}

function emitRuleType(rule: ProductionRule): string[] {
  const typeName = pascalCase(rule.name) + 'Node'
  // Flatten top-level sequences so each item becomes a named field;
  // non-sequence bodies become a single item0 field.
  const bodyItems = rule.body.kind === 'sequence' ? rule.body.items : [rule.body]
  const fieldNames = inferFieldNames(bodyItems)
  const fields = bodyItems.map((item, i) => `  ${fieldNames[i]}: ${typeForBody(item)}`)
  return [`export type ${typeName} = {`, `  kind: '${rule.name}'`, ...fields, `}`]
}

/**
 * Emit a `childNodes` helper for the given grammar.
 *
 * The generated function accepts any node in the `ParseTree` union and returns
 * a flat array of its direct ParseTree children — i.e. every `XxxNode`
 * reachable from the node's own fields, unwrapping arrays and anonymous
 * sequence objects as needed.
 *
 * Terminal strings are not included; only named rule nodes are.
 */
export function generateWalker(ast: GrammarAST, options: TypeGenOptions = {}): string {
  const treeName = options.treeName ?? 'ParseTree'
  const lines: string[] = []

  lines.push(`export function childNodes(node: ${treeName}): ${treeName}[] {`)
  lines.push(`  const children: ${treeName}[] = []`)
  lines.push(`  switch (node.kind) {`)

  for (const rule of ast.rules) {
    const bodyItems = rule.body.kind === 'sequence' ? rule.body.items : [rule.body]
    const fieldNames = inferFieldNames(bodyItems)
    const fieldStmts: string[] = []
    let varIdx = 0

    for (const [i, item] of bodyItems.entries()) {
      if (bodyContainsNonTerminal(item)) {
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        const fieldName = fieldNames[i]!
        fieldStmts.push(...childrenStmtsFor(`node.${fieldName}`, item, treeName, () => varIdx++))
      }
    }

    if (fieldStmts.length === 0) {
      lines.push(`    case '${rule.name}': break`)
    } else {
      lines.push(`    case '${rule.name}': {`)
      for (const stmt of fieldStmts) lines.push(`      ${stmt}`)
      lines.push(`      break`)
      lines.push(`    }`)
    }
  }

  lines.push(`  }`)
  lines.push(`  return children`)
  lines.push(`}`)
  lines.push(``)

  return lines.join('\n')
}

// ── Walker helpers ────────────────────────────────────────────────────────────

/** Returns true if `body` can ever yield a ParseTree node (directly or nested). */
function bodyContainsNonTerminal(body: RuleBody): boolean {
  switch (body.kind) {
    case 'nonTerminal':
      return true
    case 'terminal':
    case 'coreRule':
    case 'charValue':
      return false
    case 'sequence':
    case 'alternation':
      return body.items.some(bodyContainsNonTerminal)
    case 'optional':
    case 'zeroOrMore':
    case 'oneOrMore':
    case 'exception':
      return bodyContainsNonTerminal(body.item)
    case 'repetition':
      return bodyContainsNonTerminal(body.item)
  }
}

/**
 * Generate imperative statements that push all ParseTree children reachable
 * from `access` (which has the TypeScript type described by `body`) into a
 * local `children` array.
 */
function childrenStmtsFor(
  access: string,
  body: RuleBody,
  treeName: string,
  nextVar: () => number,
): string[] {
  switch (body.kind) {
    case 'terminal':
    case 'coreRule':
    case 'charValue':
      return []

    case 'nonTerminal':
      return [`children.push(${access})`]

    case 'exception':
      return childrenStmtsFor(access, body.item, treeName, nextVar)

    case 'optional': {
      if (!bodyContainsNonTerminal(body.item)) return []
      if (body.item.kind === 'nonTerminal') {
        return [`if (${access} !== null) children.push(${access})`]
      }
      const inner = childrenStmtsFor(access, body.item, treeName, nextVar)
      return inner.length > 0
        ? [`if (${access} !== null) {`, ...inner.map((l) => `  ${l}`), `}`]
        : []
    }

    case 'zeroOrMore':
    case 'oneOrMore':
    case 'repetition': {
      if (!bodyContainsNonTerminal(body.item)) return []
      if (body.item.kind === 'nonTerminal') {
        // Simple array of ParseTree nodes — spread directly.
        return [`children.push(...${access})`]
      }
      const v = `_item${nextVar()}`
      const inner = childrenStmtsFor(v, body.item, treeName, nextVar)
      return inner.length === 0
        ? []
        : [`for (const ${v} of ${access}) {`, ...inner.map((l) => `  ${l}`), `}`]
    }

    case 'sequence': {
      // Anonymous sequence object: extract non-terminal sub-fields by name.
      const fieldNames = inferFieldNames(body.items)
      const result: string[] = []
      for (const [i, item] of body.items.entries()) {
        if (bodyContainsNonTerminal(item)) {
          // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
          result.push(...childrenStmtsFor(`${access}.${fieldNames[i]!}`, item, treeName, nextVar))
        }
      }
      return result
    }

    case 'alternation': {
      const hasNodes = body.items.some((i) => i.kind === 'nonTerminal')
      const sequenceBranches = body.items.filter(
        (i): i is Extract<RuleBody, { kind: 'sequence' }> =>
          i.kind === 'sequence' && bodyContainsNonTerminal(i),
      )
      if (!hasNodes && sequenceBranches.length === 0) return []

      // All alternatives are ParseTree nodes, no strings or sequences.
      if (hasNodes && sequenceBranches.length === 0 && body.items.every(bodyContainsNonTerminal)) {
        return [`children.push(${access})`]
      }

      const hasStrings = body.items.some((i) => !bodyContainsNonTerminal(i))

      // Mix of nodes and strings, no anonymous sequence branches.
      if (hasNodes && sequenceBranches.length === 0 && hasStrings) {
        return [`if (typeof ${access} !== 'string') children.push(${access} as ${treeName})`]
      }

      // At least one anonymous sequence branch — need a local variable for narrowing.
      const v = `_f${nextVar()}`
      const result: string[] = [`const ${v} = ${access}`]
      const objectBody = altObjectStmts(v, hasNodes, sequenceBranches, treeName, nextVar)

      if (hasStrings) {
        result.push(`if (typeof ${v} !== 'string') {`, ...objectBody.map((l) => `  ${l}`), `}`)
      } else {
        result.push(...objectBody)
      }
      return result
    }
  }
}

/**
 * Generate statements that extract children from an object-typed alternation
 * value `v` (already narrowed past any string branch).
 */
function altObjectStmts(
  v: string,
  hasNodes: boolean,
  sequenceBranches: Array<Extract<RuleBody, { kind: 'sequence' }>>,
  treeName: string,
  nextVar: () => number,
): string[] {
  if (sequenceBranches.length === 0) {
    // Only ParseTree node branches.
    return [`children.push(${v})`]
  }
  if (!hasNodes) {
    // Only anonymous sequence branches, no direct node branches.
    return seqExtractionStmts(v, sequenceBranches, treeName, nextVar)
  }
  // Mix of node branches and sequence branches — discriminate with 'kind' in.
  return [
    `if ('kind' in ${v}) {`,
    `  children.push(${v} as ${treeName})`,
    `} else {`,
    ...seqExtractionStmts(v, sequenceBranches, treeName, nextVar).map((l) => `  ${l}`),
    `}`,
  ]
}

/**
 * Generate statements that extract ParseTree children from one or more anonymous
 * sequence branches of an alternation. Multiple branches are distinguished by
 * checking for the presence of their first non-terminal field.
 */
function seqExtractionStmts(
  v: string,
  seqItems: Array<Extract<RuleBody, { kind: 'sequence' }>>,
  treeName: string,
  nextVar: () => number,
): string[] {
  if (seqItems.length === 1) {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const seq = seqItems[0]!
    const fieldNames = inferFieldNames(seq.items)
    const result: string[] = []
    for (const [i, item] of seq.items.entries()) {
      if (bodyContainsNonTerminal(item)) {
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        result.push(...childrenStmtsFor(`${v}.${fieldNames[i]!}`, item, treeName, nextVar))
      }
    }
    return result
  }

  // Multiple sequence branches: discriminate by first non-terminal field name.
  const result: string[] = []
  for (const seq of seqItems) {
    const fieldNames = inferFieldNames(seq.items)
    const discIdx = seq.items.findIndex(bodyContainsNonTerminal)
    if (discIdx === -1) continue
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const discField = fieldNames[discIdx]!
    result.push(`if ('${discField}' in ${v}) {`)
    for (const [i, item] of seq.items.entries()) {
      if (bodyContainsNonTerminal(item)) {
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        const stmts = childrenStmtsFor(`${v}.${fieldNames[i]!}`, item, treeName, nextVar)
        for (const stmt of stmts) result.push(`  ${stmt}`)
      }
    }
    result.push(`}`)
  }
  return result
}

function camelCase(name: string): string {
  const s = name.replace(/[-_]([a-zA-Z])/g, (_, c: string) => c.toUpperCase())
  return s.charAt(0).toLowerCase() + s.slice(1)
}

function pascalCase(name: string): string {
  return name.replace(/(^|[-_])([a-zA-Z])/g, (_, __, c: string) => c.toUpperCase())
}
