/**
 * Parse tree type emitter — generates TypeScript discriminated union types
 * from a {@link GrammarAST}.
 *
 * Produces one type alias per production rule plus a root `ParseTree` union.
 */

import type { GrammarAST, ProductionRule, RuleBody } from './ast.js'

/**
 * Infer field names for a list of grammar body items.
 *
 * Non-terminal references take the camelCase of the referenced rule name.
 * All other items (terminals, core rules, composites) fall back to `item`n.
 * When the same non-terminal name appears more than once, all occurrences are
 * suffixed with a zero-based index (`year0`, `year1`, …).
 */
export function inferFieldNames(items: RuleBody[]): string[] {
  // First pass: candidate name (null = use item-n fallback)
  const candidates = items.map((item): string | null =>
    item.kind === 'nonTerminal' ? camelCase(item.name) : null,
  )

  // Count occurrences of each non-null candidate
  const counts = new Map<string, number>()
  for (const c of candidates) {
    if (c !== null) counts.set(c, (counts.get(c) ?? 0) + 1)
  }

  // Second pass: resolve duplicates with a numeric suffix
  const seen = new Map<string, number>()
  return candidates.map((candidate, i) => {
    if (candidate === null) return `item${i}`
    if ((counts.get(candidate) ?? 0) > 1) {
      const occ = seen.get(candidate) ?? 0
      seen.set(candidate, occ + 1)
      return `${candidate}${occ}`
    }
    return candidate
  })
}

/** Options for the type generator. */
export type TypeGenOptions = {
  /** Root type name for the generated union. Defaults to `'ParseTree'`. */
  treeName?: string
}

/**
 * Emit TypeScript discriminated union types for the given grammar.
 *
 * @param ast - The grammar to generate types for.
 * @param options - Optional configuration.
 * @returns A TypeScript source string containing the type definitions.
 */
export function generateTypes(ast: GrammarAST, options: TypeGenOptions = {}): string {
  const treeName = options.treeName ?? 'ParseTree'
  const lines: string[] = []

  lines.push(
    '// This file is generated by rdp-gen (@configuredthings/rdp.js). Do not edit by hand.',
  )
  lines.push('')

  for (const rule of ast.rules) {
    lines.push(...emitRuleType(rule))
    lines.push('')
  }

  // Root union
  const nodeNames = ast.rules.map((r) => pascalCase(r.name) + 'Node')
  lines.push(`export type ${treeName} =`)
  for (let i = 0; i < nodeNames.length; i++) {
    lines.push(`  | ${nodeNames[i]}`)
  }
  lines.push('')

  return lines.join('\n')
}

/**
 * Returns the TypeScript type string for a grammar body node.
 *
 * Used both by the type emitter and by `codegen.ts` when declaring capture variables.
 *
 * - Terminals, core rules, and char values → `string`
 * - Non-terminals → `XxxNode`
 * - Sequences → anonymous object type `{ item0: T0; item1: T1; ... }`
 * - Alternations → union of the alternative types
 * - Optional → `T | null`
 * - Zero-or-more, one-or-more, repetition → `T[]`
 */
export function typeForBody(body: RuleBody): string {
  switch (body.kind) {
    case 'terminal':
    case 'coreRule':
    case 'charValue':
      return 'string'
    case 'nonTerminal':
      return `${pascalCase(body.name)}Node`
    case 'sequence': {
      const names = inferFieldNames(body.items)
      return `{ ${body.items.map((item, i) => `${names[i]}: ${typeForBody(item)}`).join('; ')} }`
    }
    case 'alternation': {
      const types = [...new Set(body.items.map(typeForBody))]
      return types.join(' | ')
    }
    case 'optional':
      return `${typeForBody(body.item)} | null`
    case 'zeroOrMore':
    case 'oneOrMore':
    case 'repetition':
      return arrayType(body.item)
    case 'exception':
      return typeForBody(body.item)
  }
}

/**
 * Returns the TypeScript array type for a repeated grammar body.
 * Wraps union item types in parentheses so `A | B | C` becomes `(A | B | C)[]`
 * rather than the incorrectly-parsed `A | B | C[]`.
 */
export function arrayType(item: RuleBody): string {
  const inner = typeForBody(item)
  return inner.includes(' | ') ? `(${inner})[]` : `${inner}[]`
}

function emitRuleType(rule: ProductionRule): string[] {
  const typeName = pascalCase(rule.name) + 'Node'
  // Flatten top-level sequences so each item becomes a named field;
  // non-sequence bodies become a single item0 field.
  const bodyItems = rule.body.kind === 'sequence' ? rule.body.items : [rule.body]
  const fieldNames = inferFieldNames(bodyItems)
  const fields = bodyItems.map((item, i) => `  ${fieldNames[i]}: ${typeForBody(item)}`)
  return [`export type ${typeName} = {`, `  kind: '${rule.name}'`, ...fields, `}`]
}

function camelCase(name: string): string {
  const s = name.replace(/[-_]([a-zA-Z])/g, (_, c: string) => c.toUpperCase())
  return s.charAt(0).toLowerCase() + s.slice(1)
}

function pascalCase(name: string): string {
  return name.replace(/(^|[-_])([a-zA-Z])/g, (_, __, c: string) => c.toUpperCase())
}
