/** @module TokenRDParser */

import { RDParser } from './rdparser.js'

/**
 * The classified token stream produced by `classify()` in a span-lexer scaffold.
 *
 * - `types` — parallel array of token type codes (values from the grammar's `TT` enum)
 * - `values` — parallel array of token values (`string` for identifiers and literals,
 *   `number` for integer literals, `null` for punctuation and keywords)
 * - `len` — number of real tokens (excluding the trailing EOF sentinel)
 */
export interface TokenStream {
  types: Int32Array
  values: (string | number | null)[]
  len: number
}

/**
 * Base class for token-stream recursive descent parsers.
 *
 * Extends {@link RDParser} with token-level input handling. Receives a
 * pre-classified {@link TokenStream} produced by the span-lexer pipeline
 * (`spanTokenize` → `classify`) and provides methods for lookahead and
 * token consumption.
 *
 * Subclass this via the scaffold generated by `rdp-gen --lexer span`.
 * The generated `{Base}TokenParser` extends `TokenRDParser` and provides
 * a `static parse()` entry point that runs the full pipeline.
 */
export class TokenRDParser extends RDParser {
  readonly #types: Int32Array
  readonly #values: (string | number | null)[]
  readonly #len: number

  /**
   * @param stream - The classified token stream from `classify()`.
   */
  constructor(stream: TokenStream) {
    super()
    this.#types = stream.types
    this.#values = stream.values
    this.#len = stream.len
  }

  protected atEnd(): boolean {
    return this.getPosition() >= this.#len
  }

  protected describePosition(pos: number): string {
    if (pos >= this.#len) return 'end of input'
    const type = this.#types[pos] ?? 0
    const value = this.#values[pos]
    return value != null ? `token ${type} '${String(value)}'` : `token ${type}`
  }

  /**
   * Returns the type code of the current token without consuming it.
   * Returns `0` when at or past end of input.
   */
  protected peekToken(): number {
    return this.#types[this.getPosition()] ?? 0
  }

  /**
   * If the current token's type matches `type`, consumes it and returns its value.
   * Otherwise leaves the position unchanged and returns `null`.
   *
   * @param type - The token type code to match (a value from the grammar's `TT` enum).
   */
  protected matchToken(type: number): boolean {
    if (this.peekToken() !== type) {
      this.updateFurthestFail()
      return false
    }
    this.restorePosition(this.getPosition() + 1)
    return true
  }

  /**
   * Consumes the current token, asserting its type, and returns its value.
   *
   * @param expected - The expected token type code.
   * @param description - Optional human-readable description of the expected token, used in the error message.
   * @returns The string, number, or null value associated with the token.
   * @throws {RDParserException} If the current token's type does not match `expected`.
   */
  protected eatToken(expected: number, description?: string): string | number | null {
    const pos = this.getPosition()
    const actual = this.#types[pos]
    if (actual !== expected) {
      this.updateFurthestFail()
      const found = this.describePosition(pos)
      const expectedDesc = description ?? `token ${expected}`
      this.error(`Expected ${expectedDesc} but found ${found}`)
    }
    this.restorePosition(pos + 1)
    return this.#values[pos] ?? null
  }
}
